# -*- coding: utf-8 -*-
"""Generate TOEFL vocabulary JSON files."""
import json

# ~800 TOEFL core academic vocabulary (A-Z, alphabetical)
# Each: word, phonetic, definition, partOfSpeech, example, exampleTranslation, difficulty(2-5)
WORDS = [
    {"word": "abandon", "phonetic": "/əˈbændən/", "definition": "放弃；遗弃", "partOfSpeech": "v.", "example": "The crew had to abandon the sinking ship.", "exampleTranslation": "船员不得不放弃正在沉没的船。", "difficulty": 3},
    {"word": "abbreviate", "phonetic": "/əˈbriːvieɪt/", "definition": "缩写；简略", "partOfSpeech": "v.", "example": "PhD abbreviates Doctor of Philosophy.", "exampleTranslation": "PhD是哲学博士的缩写。", "difficulty": 4},
    {"word": "aberration", "phonetic": "/ˌæbəˈreɪʃn/", "definition": "偏离；异常", "partOfSpeech": "n.", "example": "The cold weather was an aberration for this season.", "exampleTranslation": "这种寒冷天气对这个季节来说很不寻常。", "difficulty": 5},
    {"word": "abundant", "phonetic": "/əˈbʌndənt/", "definition": "丰富的；充裕的", "partOfSpeech": "adj.", "example": "The region has abundant natural resources.", "exampleTranslation": "该地区自然资源丰富。", "difficulty": 3},
    {"word": "accelerate", "phonetic": "/əkˈseləreɪt/", "definition": "加速；促进", "partOfSpeech": "v.", "example": "The car accelerated as it entered the highway.", "exampleTranslation": "汽车进入高速公路时加速了。", "difficulty": 3},
    {"word": "accommodate", "phonetic": "/əˈkɑːmədeɪt/", "definition": "容纳；适应；提供住宿", "partOfSpeech": "v.", "example": "The hotel can accommodate 200 guests.", "exampleTranslation": "这家酒店可容纳200位客人。", "difficulty": 4},
    {"word": "account", "phonetic": "/əˈkaʊnt/", "definition": "账户；叙述；说明", "partOfSpeech": "n./v.", "example": "Can you account for your absence?", "exampleTranslation": "你能解释你缺席的原因吗？", "difficulty": 2},
    {"word": "accumulate", "phonetic": "/əˈkjuːmjəleɪt/", "definition": "积累；积聚", "partOfSpeech": "v.", "example": "Dust had accumulated on the old books.", "exampleTranslation": "灰尘在旧书上堆积。", "difficulty": 3},
    {"word": "accurate", "phonetic": "/ˈækjərət/", "definition": "准确的；精确的", "partOfSpeech": "adj.", "example": "The report provided accurate data.", "exampleTranslation": "报告提供了准确的数据。", "difficulty": 2},
    {"word": "acknowledge", "phonetic": "/əkˈnɑːlɪdʒ/", "definition": "承认；致谢", "partOfSpeech": "v.", "example": "He acknowledged his mistake publicly.", "exampleTranslation": "他公开承认了自己的错误。", "difficulty": 3},
    {"word": "acquire", "phonetic": "/əˈkwaɪər/", "definition": "获得；取得", "partOfSpeech": "v.", "example": "She acquired fluency in three languages.", "exampleTranslation": "她熟练掌握了三种语言。", "difficulty": 3},
    {"word": "adapt", "phonetic": "/əˈdæpt/", "definition": "适应；改编", "partOfSpeech": "v.", "example": "Animals must adapt to changing environments.", "exampleTranslation": "动物必须适应变化的环境。", "difficulty": 3},
    {"word": "adequate", "phonetic": "/ˈædɪkwət/", "definition": "足够的；适当的", "partOfSpeech": "adj.", "example": "We need adequate funding for the project.", "exampleTranslation": "我们需要足够的项目资金。", "difficulty": 3},
    {"word": "adjacent", "phonetic": "/əˈdʒeɪsənt/", "definition": "邻近的；毗连的", "partOfSpeech": "adj.", "example": "The library is adjacent to the student center.", "exampleTranslation": "图书馆与学生中心相邻。", "difficulty": 4},
    {"word": "adjust", "phonetic": "/əˈdʒʌst/", "definition": "调整；适应", "partOfSpeech": "v.", "example": "Please adjust the thermostat to a comfortable temperature.", "exampleTranslation": "请将恒温器调整到舒适的温度。", "difficulty": 2},
    {"word": "administration", "phonetic": "/ədˌmɪnɪˈstreɪʃn/", "definition": "管理；行政；政府", "partOfSpeech": "n.", "example": "The administration announced new policies.", "exampleTranslation": "政府宣布了新政策。", "difficulty": 3},
    {"word": "advocate", "phonetic": "/ˈædvəkeɪt/", "definition": "倡导；支持者", "partOfSpeech": "v./n.", "example": "She advocates for environmental protection.", "exampleTranslation": "她倡导环境保护。", "difficulty": 4},
    {"word": "aesthetic", "phonetic": "/iːsˈθetɪk/", "definition": "审美的；美学的", "partOfSpeech": "adj.", "example": "The building has great aesthetic appeal.", "exampleTranslation": "这座建筑具有很高的审美价值。", "difficulty": 4},
    {"word": "affect", "phonetic": "/əˈfekt/", "definition": "影响；感动", "partOfSpeech": "v.", "example": "Climate change affects ecosystems globally.", "exampleTranslation": "气候变化影响全球生态系统。", "difficulty": 2},
    {"word": "afford", "phonetic": "/əˈfɔːrd/", "definition": "负担得起；提供", "partOfSpeech": "v.", "example": "Few can afford such luxury.", "exampleTranslation": "很少有人能负担得起这种奢华。", "difficulty": 2},
    {"word": "aggregate", "phonetic": "/ˈæɡrɪɡət/", "definition": "总计；聚合", "partOfSpeech": "n./v.", "example": "The aggregate of all votes determined the winner.", "exampleTranslation": "所有选票的总和决定了获胜者。", "difficulty": 5},
    {"word": "aggressive", "phonetic": "/əˈɡresɪv/", "definition": "侵略性的；积极的", "partOfSpeech": "adj.", "example": "The company pursued an aggressive growth strategy.", "exampleTranslation": "该公司采取了积极的发展战略。", "difficulty": 3},
    {"word": "allocate", "phonetic": "/ˈæləkeɪt/", "definition": "分配；拨给", "partOfSpeech": "v.", "example": "Funds were allocated for research.", "exampleTranslation": "资金已分配给研究项目。", "difficulty": 4},
    {"word": "alternative", "phonetic": "/ɔːlˈtɜːrnətɪv/", "definition": "替代的；备选方案", "partOfSpeech": "adj./n.", "example": "We need an alternative source of energy.", "exampleTranslation": "我们需要替代能源。", "difficulty": 3},
    {"word": "ambiguous", "phonetic": "/æmˈbɪɡjuəs/", "definition": "模糊的；有歧义的", "partOfSpeech": "adj.", "example": "The instructions were ambiguous and confusing.", "exampleTranslation": "说明模糊且令人困惑。", "difficulty": 4},
    {"word": "amend", "phonetic": "/əˈmend/", "definition": "修正；修订", "partOfSpeech": "v.", "example": "The constitution was amended to extend voting rights.", "exampleTranslation": "宪法经过修订以扩大选举权。", "difficulty": 4},
    {"word": "analogy", "phonetic": "/əˈnælədʒi/", "definition": "类比；相似", "partOfSpeech": "n.", "example": "He drew an analogy between the brain and a computer.", "exampleTranslation": "他在大脑和计算机之间做了类比。", "difficulty": 4},
    {"word": "analyze", "phonetic": "/ˈænəlaɪz/", "definition": "分析；解析", "partOfSpeech": "v.", "example": "Scientists analyze the chemical composition.", "exampleTranslation": "科学家分析化学成分。", "difficulty": 2},
    {"word": "ancient", "phonetic": "/ˈeɪnʃənt/", "definition": "古代的；古老的", "partOfSpeech": "adj.", "example": "Ancient civilizations left behind many artifacts.", "exampleTranslation": "古代文明留下了许多文物。", "difficulty": 2},
    {"word": "anticipate", "phonetic": "/ænˈtɪsɪpeɪt/", "definition": "预料；期待", "partOfSpeech": "v.", "example": "We anticipate a strong turnout at the event.", "exampleTranslation": "我们预计活动将会有很多人参加。", "difficulty": 4},
    {"word": "apparatus", "phonetic": "/ˌæpəˈrætəs/", "definition": "仪器；装置", "partOfSpeech": "n.", "example": "The laboratory has sophisticated apparatus.", "exampleTranslation": "实验室拥有精密的仪器。", "difficulty": 5},
    {"word": "apparent", "phonetic": "/əˈpærənt/", "definition": "明显的；表面的", "partOfSpeech": "adj.", "example": "It was apparent that she was upset.", "exampleTranslation": "显然她很沮丧。", "difficulty": 3},
    {"word": "appeal", "phonetic": "/əˈpiːl/", "definition": "呼吁；吸引力；上诉", "partOfSpeech": "v./n.", "example": "The charity made an appeal for donations.", "exampleTranslation": "慈善机构呼吁捐款。", "difficulty": 3},
    {"word": "append", "phonetic": "/əˈpend/", "definition": "附加；追加", "partOfSpeech": "v.", "example": "Please append your signature to the document.", "exampleTranslation": "请在文件上附上您的签名。", "difficulty": 5},
    {"word": "applicable", "phonetic": "/əˈplɪkəbl/", "definition": "适用的；可应用的", "partOfSpeech": "adj.", "example": "These rules are applicable to all students.", "exampleTranslation": "这些规则适用于所有学生。", "difficulty": 4},
    {"word": "appreciate", "phonetic": "/əˈpriːʃieɪt/", "definition": "欣赏；感激；理解", "partOfSpeech": "v.", "example": "I appreciate your help with this project.", "exampleTranslation": "感谢你对这个项目的帮助。", "difficulty": 2},
    {"word": "approach", "phonetic": "/əˈproʊtʃ/", "definition": "方法；接近", "partOfSpeech": "n./v.", "example": "We need a different approach to the problem.", "exampleTranslation": "我们需要用不同的方法来解决这个问题。", "difficulty": 2},
    {"word": "appropriate", "phonetic": "/əˈproʊpriət/", "definition": "适当的；拨款", "partOfSpeech": "adj./v.", "example": "Casual attire is appropriate for this occasion.", "exampleTranslation": "便装适合这种场合。", "difficulty": 3},
    {"word": "approximate", "phonetic": "/əˈprɑːksɪmət/", "definition": "大约的；近似的", "partOfSpeech": "adj.", "example": "The approximate cost is fifty dollars.", "exampleTranslation": "大约花费五十美元。", "difficulty": 4},
    {"word": "arbitrary", "phonetic": "/ˈɑːrbɪtreri/", "definition": "武断的；任意的", "partOfSpeech": "adj.", "example": "The decision seemed arbitrary and unfair.", "exampleTranslation": "这个决定看起来武断且不公平。", "difficulty": 5},
    {"word": "architecture", "phonetic": "/ˈɑːrkɪtektʃər/", "definition": "建筑；结构", "partOfSpeech": "n.", "example": "Gothic architecture features pointed arches.", "exampleTranslation": "哥特式建筑的特点是尖拱。", "difficulty": 3},
    {"word": "ascend", "phonetic": "/əˈsend/", "definition": "上升；攀登", "partOfSpeech": "v.", "example": "The balloon ascended into the clouds.", "exampleTranslation": "气球升入云中。", "difficulty": 4},
    {"word": "aspect", "phonetic": "/ˈæspekt/", "definition": "方面；外观", "partOfSpeech": "n.", "example": "We must consider every aspect of the plan.", "exampleTranslation": "我们必须考虑计划的各个方面。", "difficulty": 3},
    {"word": "assemble", "phonetic": "/əˈsembl/", "definition": "组装；集合", "partOfSpeech": "v.", "example": "The crowd assembled in the town square.", "exampleTranslation": "人群聚集在镇广场。", "difficulty": 3},
    {"word": "assert", "phonetic": "/əˈsɜːrt/", "definition": "断言；主张", "partOfSpeech": "v.", "example": "She asserted her right to speak.", "exampleTranslation": "她坚持自己说话的权利。", "difficulty": 4},
    {"word": "assess", "phonetic": "/əˈses/", "definition": "评估；评定", "partOfSpeech": "v.", "example": "Teachers assess students' progress regularly.", "exampleTranslation": "教师定期评估学生的进步。", "difficulty": 3},
    {"word": "assume", "phonetic": "/əˈsuːm/", "definition": "假定；承担", "partOfSpeech": "v.", "example": "Let's assume that the plan will succeed.", "exampleTranslation": "我们假定计划会成功。", "difficulty": 2},
    {"word": "assure", "phonetic": "/əˈʃʊr/", "definition": "保证；使确信", "partOfSpeech": "v.", "example": "I can assure you of our full support.", "exampleTranslation": "我可以向您保证我们的全力支持。", "difficulty": 3},
    {"word": "atmosphere", "phonetic": "/ˈætməsfɪr/", "definition": "大气；气氛", "partOfSpeech": "n.", "example": "The atmosphere of Mars is thin and cold.", "exampleTranslation": "火星的大气稀薄且寒冷。", "difficulty": 2},
    {"word": "attain", "phonetic": "/əˈteɪn/", "definition": "达到；获得", "partOfSpeech": "v.", "example": "She attained her goal of graduating with honors.", "exampleTranslation": "她实现了以优异成绩毕业的目标。", "difficulty": 4},
    {"word": "attribute", "phonetic": "/əˈtrɪbjuːt/", "definition": "归因于；属性", "partOfSpeech": "v./n.", "example": "Success is often attributed to perseverance.", "exampleTranslation": "成功常被归因于坚持不懈。", "difficulty": 3},
    {"word": "authentic", "phonetic": "/ɔːˈθentɪk/", "definition": "真实的；可靠的", "partOfSpeech": "adj.", "example": "The museum displayed authentic medieval manuscripts.", "exampleTranslation": "博物馆展出了真实的中世纪手稿。", "difficulty": 4},
    {"word": "authority", "phonetic": "/əˈθɔːrəti/", "definition": "权威；当局", "partOfSpeech": "n.", "example": "The local authority approved the building plans.", "exampleTranslation": "当地政府批准了建设计划。", "difficulty": 2},
    {"word": "autonomy", "phonetic": "/ɔːˈtɑːnəmi/", "definition": "自治；自主权", "partOfSpeech": "n.", "example": "The region sought greater autonomy from the central government.", "exampleTranslation": "该地区寻求脱离中央政府的更大自治权。", "difficulty": 5},
    {"word": "available", "phonetic": "/əˈveɪləbl/", "definition": "可用的；可获得的", "partOfSpeech": "adj.", "example": "Tickets are available at the box office.", "exampleTranslation": "票房有票出售。", "difficulty": 2},
    {"word": "avert", "phonetic": "/əˈvɜːrt/", "definition": "避免；转移", "partOfSpeech": "v.", "example": "Quick action averted a disaster.", "exampleTranslation": "快速行动避免了一场灾难。", "difficulty": 5},
    {"word": "beneficial", "phonetic": "/ˌbenɪˈfɪʃl/", "definition": "有益的；有利的", "partOfSpeech": "adj.", "example": "Regular exercise is beneficial to health.", "exampleTranslation": "定期锻炼对健康有益。", "difficulty": 3},
    {"word": "bias", "phonetic": "/ˈbaɪəs/", "definition": "偏见；倾向", "partOfSpeech": "n.", "example": "The study was free from political bias.", "exampleTranslation": "这项研究没有政治偏见。", "difficulty": 4},
    {"word": "bilateral", "phonetic": "/ˌbaɪˈlætərəl/", "definition": "双边的", "partOfSpeech": "adj.", "example": "The two nations signed a bilateral trade agreement.", "exampleTranslation": "两国签署了双边贸易协定。", "difficulty": 5},
    {"word": "boundary", "phonetic": "/ˈbaʊndəri/", "definition": "边界；界限", "partOfSpeech": "n.", "example": "The river forms the boundary between the two countries.", "exampleTranslation": "这条河形成了两国的边界。", "difficulty": 3},
    {"word": "breed", "phonetic": "/briːd/", "definition": "繁殖；品种", "partOfSpeech": "v./n.", "example": "Some fish breed in fresh water.", "exampleTranslation": "有些鱼在淡水中繁殖。", "difficulty": 3},
    {"word": "brief", "phonetic": "/briːf/", "definition": "简短的；简要说明", "partOfSpeech": "adj./n.", "example": "Please give a brief summary of your findings.", "exampleTranslation": "请简要总结你的发现。", "difficulty": 2},
    {"word": "bulk", "phonetic": "/bʌlk/", "definition": "体积；大量", "partOfSpeech": "n.", "example": "The bulk of the work is already done.", "exampleTranslation": "大部分工作已经完成。", "difficulty": 4},
    {"word": "capacity", "phonetic": "/kəˈpæsəti/", "definition": "容量；能力", "partOfSpeech": "n.", "example": "The stadium has a capacity of 50,000.", "exampleTranslation": "体育场可容纳5万人。", "difficulty": 2},
    {"word": "capitol", "phonetic": "/ˈkæpɪtl/", "definition": "国会大厦", "partOfSpeech": "n.", "example": "The Capitol building houses the U.S. Congress.", "exampleTranslation": "国会大厦是美国国会所在地。", "difficulty": 4},
    {"word": "capture", "phonetic": "/ˈkæptʃər/", "definition": "捕获；捕捉", "partOfSpeech": "v.", "example": "The photograph captures the essence of the moment.", "exampleTranslation": "这张照片捕捉到了那一刻的精髓。", "difficulty": 3},
    {"word": "cardinal", "phonetic": "/ˈkɑːrdɪnl/", "definition": "主要的；基本的", "partOfSpeech": "adj.", "example": "Honesty is a cardinal virtue.", "exampleTranslation": "诚实是一项基本美德。", "difficulty": 5},
    {"word": "catastrophe", "phonetic": "/kəˈtæstrəfi/", "definition": "大灾难", "partOfSpeech": "n.", "example": "The earthquake was a natural catastrophe.", "exampleTranslation": "地震是一场自然灾害。", "difficulty": 5},
    {"word": "categorize", "phonetic": "/ˈkætəɡəraɪz/", "definition": "分类；归类", "partOfSpeech": "v.", "example": "Books are categorized by subject.", "exampleTranslation": "书籍按主题分类。", "difficulty": 4},
    {"word": "cease", "phonetic": "/siːs/", "definition": "停止；终止", "partOfSpeech": "v.", "example": "The rain ceased at dawn.", "exampleTranslation": "黎明时分雨停了。", "difficulty": 4},
    {"word": "challenge", "phonetic": "/ˈtʃælɪndʒ/", "definition": "挑战；质疑", "partOfSpeech": "n./v.", "example": "Climate change poses a major challenge.", "exampleTranslation": "气候变化是一个重大挑战。", "difficulty": 2},
    {"word": "characteristic", "phonetic": "/ˌkærəktəˈrɪstɪk/", "definition": "特征；特点", "partOfSpeech": "n./adj.", "example": "Patience is a characteristic of good teachers.", "exampleTranslation": "耐心是好老师的特征。", "difficulty": 3},
    {"word": "chemical", "phonetic": "/ˈkemɪkl/", "definition": "化学的；化学制品", "partOfSpeech": "adj./n.", "example": "Chemical reactions occur when substances combine.", "exampleTranslation": "物质结合时会发生化学反应。", "difficulty": 2},
    {"word": "chronological", "phonetic": "/ˌkrɑːnəˈlɑːdʒɪkl/", "definition": "按时间顺序的", "partOfSpeech": "adj.", "example": "The events are listed in chronological order.", "exampleTranslation": "事件按时间顺序列出。", "difficulty": 5},
    {"word": "circumstance", "phonetic": "/ˈsɜːrkəmstæns/", "definition": "情况；环境", "partOfSpeech": "n.", "example": "Under no circumstances should you give up.", "exampleTranslation": "无论何种情况你都不应放弃。", "difficulty": 3},
    {"word": "cite", "phonetic": "/saɪt/", "definition": "引用；传唤", "partOfSpeech": "v.", "example": "Always cite your sources in academic writing.", "exampleTranslation": "学术写作中务必引用资料来源。", "difficulty": 4},
    {"word": "civilization", "phonetic": "/ˌsɪvələˈzeɪʃn/", "definition": "文明", "partOfSpeech": "n.", "example": "Ancient Egyptian civilization thrived along the Nile.", "exampleTranslation": "古埃及文明在尼罗河畔繁盛。", "difficulty": 3},
    {"word": "clarify", "phonetic": "/ˈklærəfaɪ/", "definition": "澄清；阐明", "partOfSpeech": "v.", "example": "Let me clarify what I meant.", "exampleTranslation": "让我澄清我的意思。", "difficulty": 3},
    {"word": "classify", "phonetic": "/ˈklæsɪfaɪ/", "definition": "分类；分级", "partOfSpeech": "v.", "example": "Scientists classify animals into different phyla.", "exampleTranslation": "科学家将动物分为不同的门类。", "difficulty": 3},
    {"word": "coincide", "phonetic": "/ˌkoʊɪnˈsaɪd/", "definition": "同时发生；一致", "partOfSpeech": "v.", "example": "Our views coincide on most issues.", "exampleTranslation": "我们在大多数问题上看法一致。", "difficulty": 5},
    {"word": "collapse", "phonetic": "/kəˈlæps/", "definition": "崩塌；崩溃", "partOfSpeech": "v.", "example": "The old bridge collapsed during the flood.", "exampleTranslation": "旧桥在洪水期间倒塌了。", "difficulty": 3},
    {"word": "colleague", "phonetic": "/ˈkɑːliːɡ/", "definition": "同事；同行", "partOfSpeech": "n.", "example": "She discussed the project with her colleagues.", "exampleTranslation": "她和同事讨论了项目。", "difficulty": 2},
    {"word": "commence", "phonetic": "/kəˈmens/", "definition": "开始", "partOfSpeech": "v.", "example": "The ceremony will commence at noon.", "exampleTranslation": "仪式将于中午开始。", "difficulty": 4},
    {"word": "comment", "phonetic": "/ˈkɑːment/", "definition": "评论；意见", "partOfSpeech": "n./v.", "example": "Would you like to comment on the proposal?", "exampleTranslation": "您想对提案发表评论吗？", "difficulty": 2},
    {"word": "commission", "phonetic": "/kəˈmɪʃn/", "definition": "委员会；委托", "partOfSpeech": "n./v.", "example": "The artist was commissioned to paint a mural.", "exampleTranslation": "这位艺术家受托绘制壁画。", "difficulty": 3},
    {"word": "commit", "phonetic": "/kəˈmɪt/", "definition": "承诺；犯（罪）", "partOfSpeech": "v.", "example": "The company is committed to sustainability.", "exampleTranslation": "该公司致力于可持续发展。", "difficulty": 2},
    {"word": "commodity", "phonetic": "/kəˈmɑːdəti/", "definition": "商品；日用品", "partOfSpeech": "n.", "example": "Oil is a valuable commodity in global trade.", "exampleTranslation": "石油是全球贸易中的宝贵商品。", "difficulty": 5},
    {"word": "communicate", "phonetic": "/kəˈmjuːnɪkeɪt/", "definition": "沟通；传达", "partOfSpeech": "v.", "example": "Birds communicate through songs and calls.", "exampleTranslation": "鸟类通过鸣叫进行交流。", "difficulty": 2},
    {"word": "community", "phonetic": "/kəˈmjuːnəti/", "definition": "社区；团体", "partOfSpeech": "n.", "example": "The local community supported the initiative.", "exampleTranslation": "当地社区支持了这一倡议。", "difficulty": 2},
    {"word": "compatible", "phonetic": "/kəmˈpætəbl/", "definition": "兼容的；可共存的", "partOfSpeech": "adj.", "example": "The software is compatible with Windows and Mac.", "exampleTranslation": "该软件与Windows和Mac兼容。", "difficulty": 4},
    {"word": "compensate", "phonetic": "/ˈkɑːmpənseɪt/", "definition": "补偿；抵消", "partOfSpeech": "v.", "example": "The company compensated victims for their losses.", "exampleTranslation": "公司对受害者的损失进行了赔偿。", "difficulty": 4},
    {"word": "compile", "phonetic": "/kəmˈpaɪl/", "definition": "编译；汇集", "partOfSpeech": "v.", "example": "Researchers compiled data from multiple sources.", "exampleTranslation": "研究人员从多个来源汇集了数据。", "difficulty": 5},
    {"word": "complement", "phonetic": "/ˈkɑːmplɪment/", "definition": "补充；补足", "partOfSpeech": "v./n.", "example": "The wine complements the meal perfectly.", "exampleTranslation": "这酒与菜肴完美搭配。", "difficulty": 4},
    {"word": "complex", "phonetic": "/ˈkɑːmpleks/", "definition": "复杂的；复合体", "partOfSpeech": "adj./n.", "example": "The human brain is extremely complex.", "exampleTranslation": "人类大脑极其复杂。", "difficulty": 2},
    {"word": "component", "phonetic": "/kəmˈpoʊnənt/", "definition": "组成部分；组件", "partOfSpeech": "n.", "example": "Trust is a key component of any relationship.", "exampleTranslation": "信任是任何关系的关键组成部分。", "difficulty": 3},
    {"word": "compound", "phonetic": "/ˈkɑːmpaʊnd/", "definition": "化合物；复合的", "partOfSpeech": "n./adj.", "example": "Water is a compound of hydrogen and oxygen.", "exampleTranslation": "水是氢和氧的化合物。", "difficulty": 3},
    {"word": "comprehensive", "phonetic": "/ˌkɑːmprɪˈhensɪv/", "definition": "全面的；综合的", "partOfSpeech": "adj.", "example": "We need a comprehensive review of the policy.", "exampleTranslation": "我们需要对政策进行全面审查。", "difficulty": 4},
    {"word": "comprise", "phonetic": "/kəmˈpraɪz/", "definition": "包含；由...组成", "partOfSpeech": "v.", "example": "The committee comprises ten members.", "exampleTranslation": "委员会由十名成员组成。", "difficulty": 4},
    {"word": "concentrate", "phonetic": "/ˈkɑːnsəntreɪt/", "definition": "集中；专心", "partOfSpeech": "v.", "example": "I need to concentrate on my work.", "exampleTranslation": "我需要专注于工作。", "difficulty": 2},
    {"word": "concept", "phonetic": "/ˈkɑːnsept/", "definition": "概念；观念", "partOfSpeech": "n.", "example": "The concept of democracy has evolved over time.", "exampleTranslation": "民主的概念随着时间而演变。", "difficulty": 2},
    {"word": "conclude", "phonetic": "/kənˈkluːd/", "definition": "得出结论；结束", "partOfSpeech": "v.", "example": "The study concluded that the treatment is effective.", "exampleTranslation": "研究得出结论：该治疗是有效的。", "difficulty": 2},
    {"word": "concrete", "phonetic": "/ˈkɑːnkriːt/", "definition": "具体的；混凝土", "partOfSpeech": "adj./n.", "example": "We need concrete evidence before proceeding.", "exampleTranslation": "我们需要具体证据才能继续。", "difficulty": 2},
    {"word": "conduct", "phonetic": "/kənˈdʌkt/", "definition": "进行；行为", "partOfSpeech": "v./n.", "example": "The team conducted a series of experiments.", "exampleTranslation": "团队进行了一系列实验。", "difficulty": 2},
    {"word": "confer", "phonetic": "/kənˈfɜːr/", "definition": "授予；商谈", "partOfSpeech": "v.", "example": "The university will confer the degree next month.", "exampleTranslation": "大学将于下月授予学位。", "difficulty": 5},
    {"word": "confine", "phonetic": "/kənˈfaɪn/", "definition": "限制；禁闭", "partOfSpeech": "v.", "example": "The outbreak was confined to the northern region.", "exampleTranslation": "疫情仅限于北部地区。", "difficulty": 5},
    {"word": "confirm", "phonetic": "/kənˈfɜːrm/", "definition": "确认；证实", "partOfSpeech": "v.", "example": "Please confirm your attendance by Friday.", "exampleTranslation": "请于周五前确认您的出席。", "difficulty": 2},
    {"word": "conflict", "phonetic": "/ˈkɑːnflɪkt/", "definition": "冲突；矛盾", "partOfSpeech": "n./v.", "example": "The conflict between the two nations escalated.", "exampleTranslation": "两国之间的冲突升级了。", "difficulty": 2},
    {"word": "conform", "phonetic": "/kənˈfɔːrm/", "definition": "遵从；符合", "partOfSpeech": "v.", "example": "Students must conform to the dress code.", "exampleTranslation": "学生必须遵守着装规定。", "difficulty": 4},
    {"word": "confront", "phonetic": "/kənˈfrʌnt/", "definition": "面对；对抗", "partOfSpeech": "v.", "example": "We must confront our challenges directly.", "exampleTranslation": "我们必须直接面对挑战。", "difficulty": 3},
    {"word": "confuse", "phonetic": "/kənˈfjuːz/", "definition": "使困惑；混淆", "partOfSpeech": "v.", "example": "The instructions confused many users.", "exampleTranslation": "说明使许多用户感到困惑。", "difficulty": 2},
    {"word": "conscious", "phonetic": "/ˈkɑːnʃəs/", "definition": "有意识的；自觉的", "partOfSpeech": "adj.", "example": "She made a conscious decision to change careers.", "exampleTranslation": "她有意识地决定换工作。", "difficulty": 2},
    {"word": "consecutive", "phonetic": "/kənˈsekjətɪv/", "definition": "连续的；接连的", "partOfSpeech": "adj.", "example": "It rained for five consecutive days.", "exampleTranslation": "连续下了五天雨。", "difficulty": 5},
    {"word": "consensus", "phonetic": "/kənˈsensəs/", "definition": "共识；一致意见", "partOfSpeech": "n.", "example": "There is broad consensus on climate action.", "exampleTranslation": "在气候行动上存在广泛共识。", "difficulty": 4},
    {"word": "consequence", "phonetic": "/ˈkɑːnsɪkwens/", "definition": "结果；后果", "partOfSpeech": "n.", "example": "We must consider the consequences of our actions.", "exampleTranslation": "我们必须考虑我们行动的后果。", "difficulty": 2},
    {"word": "conserve", "phonetic": "/kənˈsɜːrv/", "definition": "保护；保存", "partOfSpeech": "v.", "example": "We must conserve our natural resources.", "exampleTranslation": "我们必须保护我们的自然资源。", "difficulty": 4},
    {"word": "considerable", "phonetic": "/kənˈsɪdərəbl/", "definition": "相当大的；可观的", "partOfSpeech": "adj.", "example": "The project requires considerable funding.", "exampleTranslation": "该项目需要相当多的资金。", "difficulty": 3},
    {"word": "consist", "phonetic": "/kənˈsɪst/", "definition": "组成；在于", "partOfSpeech": "v.", "example": "The diet consists mainly of fruits and vegetables.", "exampleTranslation": "饮食主要由水果和蔬菜组成。", "difficulty": 2},
    {"word": "consistent", "phonetic": "/kənˈsɪstənt/", "definition": "一致的；始终如一的", "partOfSpeech": "adj.", "example": "Her performance has been consistent throughout the season.", "exampleTranslation": "她整个赛季的表现一直很稳定。", "difficulty": 3},
    {"word": "constant", "phonetic": "/ˈkɑːnstənt/", "definition": "持续的；恒定的", "partOfSpeech": "adj.", "example": "The temperature remained constant.", "exampleTranslation": "温度保持恒定。", "difficulty": 2},
    {"word": "constitute", "phonetic": "/ˈkɑːnstɪtuːt/", "definition": "构成；组成", "partOfSpeech": "v.", "example": "Women constitute half of the workforce.", "exampleTranslation": "女性构成劳动力的一半。", "difficulty": 4},
    {"word": "constraint", "phonetic": "/kənˈstreɪnt/", "definition": "约束；限制", "partOfSpeech": "n.", "example": "Budget constraints limited the project scope.", "exampleTranslation": "预算限制制约了项目范围。", "difficulty": 5},
    {"word": "construct", "phonetic": "/kənˈstrʌkt/", "definition": "建造；构建", "partOfSpeech": "v.", "example": "They plan to construct a new bridge.", "exampleTranslation": "他们计划建造一座新桥。", "difficulty": 2},
    {"word": "consult", "phonetic": "/kənˈsʌlt/", "definition": "咨询；查阅", "partOfSpeech": "v.", "example": "Consult a doctor if symptoms persist.", "exampleTranslation": "如果症状持续，请咨询医生。", "difficulty": 2},
    {"word": "consume", "phonetic": "/kənˈsuːm/", "definition": "消费；消耗", "partOfSpeech": "v.", "example": "The engine consumes less fuel now.", "exampleTranslation": "发动机现在消耗的燃料更少。", "difficulty": 2},
    {"word": "contact", "phonetic": "/ˈkɑːntækt/", "definition": "接触；联系", "partOfSpeech": "n./v.", "example": "Please contact us if you have questions.", "exampleTranslation": "如有问题请联系我们。", "difficulty": 2},
    {"word": "contemporary", "phonetic": "/kənˈtempəreri/", "definition": "当代的；同时代的", "partOfSpeech": "adj.", "example": "Contemporary art often challenges tradition.", "exampleTranslation": "当代艺术常常挑战传统。", "difficulty": 4},
    {"word": "context", "phonetic": "/ˈkɑːntekst/", "definition": "上下文；背景", "partOfSpeech": "n.", "example": "Words must be understood in context.", "exampleTranslation": "词语必须在上下文中理解。", "difficulty": 2},
    {"word": "contract", "phonetic": "/ˈkɑːntrækt/", "definition": "合同；收缩", "partOfSpeech": "n./v.", "example": "Both parties signed the contract.", "exampleTranslation": "双方签署了合同。", "difficulty": 2},
    {"word": "contradict", "phonetic": "/ˌkɑːntrəˈdɪkt/", "definition": "矛盾；反驳", "partOfSpeech": "v.", "example": "His actions contradict his words.", "exampleTranslation": "他的行动与他的话相矛盾。", "difficulty": 4},
    {"word": "contrary", "phonetic": "/ˈkɑːntreri/", "definition": "相反的；对立面", "partOfSpeech": "adj./n.", "example": "Contrary to expectations, sales increased.", "exampleTranslation": "与预期相反，销售额增加了。", "difficulty": 3},
    {"word": "contrast", "phonetic": "/ˈkɑːntræst/", "definition": "对比；对照", "partOfSpeech": "n./v.", "example": "The contrast between rich and poor is striking.", "exampleTranslation": "贫富差距令人震惊。", "difficulty": 2},
    {"word": "contribute", "phonetic": "/kənˈtrɪbjuːt/", "definition": "贡献；促成", "partOfSpeech": "v.", "example": "Everyone can contribute to the project.", "exampleTranslation": "每个人都可以为项目做贡献。", "difficulty": 2},
    {"word": "controversy", "phonetic": "/ˈkɑːntrəvɜːrsi/", "definition": "争议；争论", "partOfSpeech": "n.", "example": "The policy sparked controversy among experts.", "exampleTranslation": "该政策在专家中引发争议。", "difficulty": 4},
    {"word": "convene", "phonetic": "/kənˈviːn/", "definition": "召集；召开", "partOfSpeech": "v.", "example": "The committee will convene next week.", "exampleTranslation": "委员会将于下周召开会议。", "difficulty": 5},
    {"word": "conventional", "phonetic": "/kənˈvenʃənl/", "definition": "传统的；常规的", "partOfSpeech": "adj.", "example": "They chose a conventional approach.", "exampleTranslation": "他们选择了传统方法。", "difficulty": 3},
    {"word": "convert", "phonetic": "/kənˈvɜːrt/", "definition": "转换；转变", "partOfSpeech": "v.", "example": "Solar panels convert sunlight into electricity.", "exampleTranslation": "太阳能电池板将阳光转化为电能。", "difficulty": 3},
    {"word": "convey", "phonetic": "/kənˈveɪ/", "definition": "传达；运输", "partOfSpeech": "v.", "example": "Art can convey powerful emotions.", "exampleTranslation": "艺术可以传达强烈的情感。", "difficulty": 4},
    {"word": "convince", "phonetic": "/kənˈvɪns/", "definition": "说服；使确信", "partOfSpeech": "v.", "example": "The evidence convinced the jury.", "exampleTranslation": "证据使陪审团信服。", "difficulty": 2},
    {"word": "coordinate", "phonetic": "/koʊˈɔːrdɪneɪt/", "definition": "协调；使配合", "partOfSpeech": "v.", "example": "We need to coordinate our efforts.", "exampleTranslation": "我们需要协调我们的努力。", "difficulty": 3},
    {"word": "core", "phonetic": "/kɔːr/", "definition": "核心；要点", "partOfSpeech": "n./adj.", "example": "Honesty is at the core of their values.", "exampleTranslation": "诚实是他们价值观的核心。", "difficulty": 2},
    {"word": "corporate", "phonetic": "/ˈkɔːrpərət/", "definition": "公司的；法人的", "partOfSpeech": "adj.", "example": "Corporate culture varies by company.", "exampleTranslation": "企业文化因公司而异。", "difficulty": 3},
    {"word": "correspond", "phonetic": "/ˌkɔːrəˈspɑːnd/", "definition": "一致；通信", "partOfSpeech": "v.", "example": "The results correspond to our predictions.", "exampleTranslation": "结果与我们的预测一致。", "difficulty": 5},
    {"word": "corridor", "phonetic": "/ˈkɔːrɪdɔːr/", "definition": "走廊；通道", "partOfSpeech": "n.", "example": "The corridor leads to the main hall.", "exampleTranslation": "走廊通向大厅。", "difficulty": 3},
    {"word": "crucial", "phonetic": "/ˈkruːʃl/", "definition": "关键的；至关重要的", "partOfSpeech": "adj.", "example": "Timing is crucial for success.", "exampleTranslation": "时机对成功至关重要。", "difficulty": 3},
    {"word": "cultivate", "phonetic": "/ˈkʌltɪveɪt/", "definition": "培养；耕作", "partOfSpeech": "v.", "example": "She cultivated a love of reading in her students.", "exampleTranslation": "她培养了学生对阅读的热爱。", "difficulty": 4},
    {"word": "curriculum", "phonetic": "/kəˈrɪkjələm/", "definition": "课程；教学大纲", "partOfSpeech": "n.", "example": "The curriculum has been updated this year.", "exampleTranslation": "今年课程已经更新。", "difficulty": 4},
    {"word": "decade", "phonetic": "/ˈdekeɪd/", "definition": "十年", "partOfSpeech": "n.", "example": "Technology has changed dramatically in the past decade.", "exampleTranslation": "过去十年技术发生了巨大变化。", "difficulty": 2},
    {"word": "decline", "phonetic": "/dɪˈklaɪn/", "definition": "下降；拒绝", "partOfSpeech": "v./n.", "example": "Fish populations have declined sharply.", "exampleTranslation": "鱼类数量急剧下降。", "difficulty": 2},
    {"word": "deduce", "phonetic": "/dɪˈduːs/", "definition": "推论；演绎", "partOfSpeech": "v.", "example": "From the evidence, we can deduce his guilt.", "exampleTranslation": "从证据中我们可以推断他有罪。", "difficulty": 5},
    {"word": "define", "phonetic": "/dɪˈfaɪn/", "definition": "定义；界定", "partOfSpeech": "v.", "example": "It is difficult to define beauty.", "exampleTranslation": "很难给美下定义。", "difficulty": 2},
    {"word": "definite", "phonetic": "/ˈdefɪnət/", "definition": "明确的；确定的", "partOfSpeech": "adj.", "example": "We need a definite answer by tomorrow.", "exampleTranslation": "我们需要在明天之前得到明确答复。", "difficulty": 2},
    {"word": "demonstrate", "phonetic": "/ˈdemənstreɪt/", "definition": "证明；展示", "partOfSpeech": "v.", "example": "The experiment demonstrated the theory.", "exampleTranslation": "实验证明了该理论。", "difficulty": 2},
    {"word": "denote", "phonetic": "/dɪˈnoʊt/", "definition": "表示；象征", "partOfSpeech": "v.", "example": "In this equation, x denotes the unknown variable.", "exampleTranslation": "在这个方程中，x表示未知变量。", "difficulty": 5},
    {"word": "density", "phonetic": "/ˈdensəti/", "definition": "密度", "partOfSpeech": "n.", "example": "The population density is high in cities.", "exampleTranslation": "城市的人口密度很高。", "difficulty": 3},
    {"word": "deny", "phonetic": "/dɪˈnaɪ/", "definition": "否认；拒绝", "partOfSpeech": "v.", "example": "He denied any involvement in the crime.", "exampleTranslation": "他否认与犯罪有任何牵连。", "difficulty": 2},
    {"word": "depict", "phonetic": "/dɪˈpɪkt/", "definition": "描绘；描述", "partOfSpeech": "v.", "example": "The mural depicts scenes from history.", "exampleTranslation": "壁画描绘了历史场景。", "difficulty": 4},
    {"word": "deplete", "phonetic": "/dɪˈpliːt/", "definition": "耗尽；使枯竭", "partOfSpeech": "v.", "example": "Overfishing has depleted fish stocks.", "exampleTranslation": "过度捕捞使鱼类资源枯竭。", "difficulty": 5},
    {"word": "derive", "phonetic": "/dɪˈraɪv/", "definition": "源于；推导", "partOfSpeech": "v.", "example": "Many English words derive from Latin.", "exampleTranslation": "许多英语词源于拉丁语。", "difficulty": 4},
    {"word": "designate", "phonetic": "/ˈdezɪɡneɪt/", "definition": "指定；命名", "partOfSpeech": "v.", "example": "The area was designated as a nature reserve.", "exampleTranslation": "该地区被指定为自然保护区。", "difficulty": 5},
    {"word": "despite", "phonetic": "/dɪˈspaɪt/", "definition": "尽管；任凭", "partOfSpeech": "prep.", "example": "She succeeded despite the obstacles.", "exampleTranslation": "尽管有障碍，她还是成功了。", "difficulty": 2},
    {"word": "detect", "phonetic": "/dɪˈtekt/", "definition": "察觉；探测", "partOfSpeech": "v.", "example": "The device can detect radon gas.", "exampleTranslation": "该设备可以探测氡气。", "difficulty": 3},
    {"word": "deteriorate", "phonetic": "/dɪˈtɪriəreɪt/", "definition": "恶化；退化", "partOfSpeech": "v.", "example": "His health deteriorated rapidly.", "exampleTranslation": "他的健康状况迅速恶化。", "difficulty": 5},
    {"word": "determine", "phonetic": "/dɪˈtɜːrmɪn/", "definition": "确定；决定", "partOfSpeech": "v.", "example": "The court will determine the outcome.", "exampleTranslation": "法院将决定结果。", "difficulty": 2},
    {"word": "devastate", "phonetic": "/ˈdevəsteɪt/", "definition": "摧毁；使荒芜", "partOfSpeech": "v.", "example": "The hurricane devastated the coastal towns.", "exampleTranslation": "飓风摧毁了沿海城镇。", "difficulty": 5},
    {"word": "device", "phonetic": "/dɪˈvaɪs/", "definition": "设备；装置", "partOfSpeech": "n.", "example": "The device measures air quality.", "exampleTranslation": "该设备测量空气质量。", "difficulty": 2},
    {"word": "differentiate", "phonetic": "/ˌdɪfəˈrenʃieɪt/", "definition": "区分；辨别", "partOfSpeech": "v.", "example": "It is hard to differentiate the two species.", "exampleTranslation": "很难区分这两个物种。", "difficulty": 5},
    {"word": "diffuse", "phonetic": "/dɪˈfjuːz/", "definition": "扩散；散开", "partOfSpeech": "v.", "example": "Light diffuses through the cloudy glass.", "exampleTranslation": "光线透过磨砂玻璃扩散。", "difficulty": 5},
    {"word": "dimension", "phonetic": "/daɪˈmenʃn/", "definition": "维度；尺寸", "partOfSpeech": "n.", "example": "We must consider the social dimension.", "exampleTranslation": "我们必须考虑社会层面。", "difficulty": 3},
    {"word": "diminish", "phonetic": "/dɪˈmɪnɪʃ/", "definition": "减少；缩小", "partOfSpeech": "v.", "example": "Resources have diminished over time.", "exampleTranslation": "资源随时间减少。", "difficulty": 4},
    {"word": "discard", "phonetic": "/dɪsˈkɑːrd/", "definition": "丢弃；抛弃", "partOfSpeech": "v.", "example": "Do not discard batteries in regular trash.", "exampleTranslation": "不要将电池丢弃在普通垃圾中。", "difficulty": 4},
    {"word": "discern", "phonetic": "/dɪˈsɜːrn/", "definition": "辨明；觉察", "partOfSpeech": "v.", "example": "It was hard to discern his true intentions.", "exampleTranslation": "很难辨明他的真实意图。", "difficulty": 5},
    {"word": "discipline", "phonetic": "/ˈdɪsəplɪn/", "definition": "学科；纪律", "partOfSpeech": "n.", "example": "Biology is a scientific discipline.", "exampleTranslation": "生物学是一门科学学科。", "difficulty": 2},
    {"word": "disclose", "phonetic": "/dɪsˈkloʊz/", "definition": "揭露；透露", "partOfSpeech": "v.", "example": "The company disclosed its financial results.", "exampleTranslation": "公司披露了财务业绩。", "difficulty": 4},
    {"word": "discrete", "phonetic": "/dɪˈskriːt/", "definition": "分离的；离散的", "partOfSpeech": "adj.", "example": "The data points are discrete entities.", "exampleTranslation": "数据点是离散的实体。", "difficulty": 5},
    {"word": "discriminate", "phonetic": "/dɪˈskrɪmɪneɪt/", "definition": "歧视；区分", "partOfSpeech": "v.", "example": "It is illegal to discriminate based on race.", "exampleTranslation": "基于种族的歧视是非法的。", "difficulty": 4},
    {"word": "dispose", "phonetic": "/dɪˈspoʊz/", "definition": "处置；安排", "partOfSpeech": "v.", "example": "Properly dispose of hazardous waste.", "exampleTranslation": "妥善处置危险废物。", "difficulty": 4},
    {"word": "dispute", "phonetic": "/dɪˈspjuːt/", "definition": "争议；争论", "partOfSpeech": "n./v.", "example": "The border dispute escalated into conflict.", "exampleTranslation": "边境争端升级为冲突。", "difficulty": 3},
    {"word": "dissolve", "phonetic": "/dɪˈzɑːlv/", "definition": "溶解；解散", "partOfSpeech": "v.", "example": "Salt dissolves in water.", "exampleTranslation": "盐溶于水。", "difficulty": 3},
    {"word": "distinct", "phonetic": "/dɪˈstɪŋkt/", "definition": "明显的；独特的", "partOfSpeech": "adj.", "example": "The two species have distinct characteristics.", "exampleTranslation": "这两个物种有不同的特征。", "difficulty": 2},
    {"word": "distinguish", "phonetic": "/dɪˈstɪŋɡwɪʃ/", "definition": "区分；辨别", "partOfSpeech": "v.", "example": "It is hard to distinguish between them.", "exampleTranslation": "很难区分它们。", "difficulty": 2},
    {"word": "distribute", "phonetic": "/dɪˈstrɪbjuːt/", "definition": "分配；分布", "partOfSpeech": "v.", "example": "We distributed flyers to local residents.", "exampleTranslation": "我们向当地居民分发传单。", "difficulty": 2},
    {"word": "diverse", "phonetic": "/daɪˈvɜːrs/", "definition": "多样的；不同的", "partOfSpeech": "adj.", "example": "The team has a diverse background.", "exampleTranslation": "团队背景多样。", "difficulty": 2},
    {"word": "document", "phonetic": "/ˈdɑːkjument/", "definition": "文件；记录", "partOfSpeech": "n./v.", "example": "Please document your findings.", "exampleTranslation": "请记录你的发现。", "difficulty": 2},
    {"word": "domestic", "phonetic": "/dəˈmestɪk/", "definition": "国内的；家养的", "partOfSpeech": "adj.", "example": "Domestic policy differs from foreign policy.", "exampleTranslation": "国内政策不同于外交政策。", "difficulty": 2},
    {"word": "dominant", "phonetic": "/ˈdɑːmɪnənt/", "definition": "主要的；显性的", "partOfSpeech": "adj.", "example": "English is the dominant language in business.", "exampleTranslation": "英语是商业中的主要语言。", "difficulty": 3},
    {"word": "dormant", "phonetic": "/ˈdɔːrmənt/", "definition": "休眠的；潜伏的", "partOfSpeech": "adj.", "example": "The volcano has been dormant for centuries.", "exampleTranslation": "这座火山已经休眠了几个世纪。", "difficulty": 5},
    {"word": "duration", "phonetic": "/duˈreɪʃn/", "definition": "持续期间", "partOfSpeech": "n.", "example": "The duration of the course is ten weeks.", "exampleTranslation": "课程为期十周。", "difficulty": 3},
    {"word": "dynamic", "phonetic": "/daɪˈnæmɪk/", "definition": "动态的；有活力的", "partOfSpeech": "adj.", "example": "The market is highly dynamic.", "exampleTranslation": "市场极具活力。", "difficulty": 3},
    {"word": "economy", "phonetic": "/ɪˈkɑːnəmi/", "definition": "经济；节俭", "partOfSpeech": "n.", "example": "The global economy is interconnected.", "exampleTranslation": "全球经济相互关联。", "difficulty": 2},
    {"word": "efficient", "phonetic": "/ɪˈfɪʃnt/", "definition": "高效的；有效的", "partOfSpeech": "adj.", "example": "The new system is more efficient.", "exampleTranslation": "新系统更高效。", "difficulty": 2},
    {"word": "elaborate", "phonetic": "/ɪˈlæbərət/", "definition": "详尽的；精心制作的", "partOfSpeech": "adj./v.", "example": "Could you elaborate on that point?", "exampleTranslation": "您能详细说明那一点吗？", "difficulty": 3},
    {"word": "eliminate", "phonetic": "/ɪˈlɪmɪneɪt/", "definition": "消除；淘汰", "partOfSpeech": "v.", "example": "We must eliminate all sources of error.", "exampleTranslation": "我们必须消除所有错误来源。", "difficulty": 2},
    {"word": "elude", "phonetic": "/ɪˈluːd/", "definition": "躲避；逃避", "partOfSpeech": "v.", "example": "The suspect eluded the police for weeks.", "exampleTranslation": "嫌疑犯躲避警方数周。", "difficulty": 5},
    {"word": "emerge", "phonetic": "/ɪˈmɜːrdʒ/", "definition": "出现；浮现", "partOfSpeech": "v.", "example": "A new leader emerged from the crisis.", "exampleTranslation": "一位新领袖从危机中脱颖而出。", "difficulty": 2},
    {"word": "emphasis", "phonetic": "/ˈemfəsɪs/", "definition": "强调；重点", "partOfSpeech": "n.", "example": "The course places emphasis on practical skills.", "exampleTranslation": "该课程强调实践技能。", "difficulty": 3},
    {"word": "empirical", "phonetic": "/ɪmˈpɪrɪkl/", "definition": "经验主义的；以观察为依据的", "partOfSpeech": "adj.", "example": "The study is based on empirical evidence.", "exampleTranslation": "该研究基于经验证据。", "difficulty": 5},
    {"word": "enable", "phonetic": "/ɪˈneɪbl/", "definition": "使能够；使可能", "partOfSpeech": "v.", "example": "Technology enables remote work.", "exampleTranslation": "技术使远程工作成为可能。", "difficulty": 2},
    {"word": "encounter", "phonetic": "/ɪnˈkaʊntər/", "definition": "遭遇；遇见", "partOfSpeech": "v./n.", "example": "We may encounter obstacles along the way.", "exampleTranslation": "我们可能会遇到障碍。", "difficulty": 2},
    {"word": "endure", "phonetic": "/ɪnˈdʊr/", "definition": "忍受；持续", "partOfSpeech": "v.", "example": "She endured years of hardship.", "exampleTranslation": "她忍受了多年的艰难。", "difficulty": 3},
    {"word": "enhance", "phonetic": "/ɪnˈhæns/", "definition": "增强；提高", "partOfSpeech": "v.", "example": "Exercise enhances mental clarity.", "exampleTranslation": "锻炼能提高思维清晰度。", "difficulty": 2},
    {"word": "enormous", "phonetic": "/ɪˈnɔːrməs/", "definition": "巨大的；庞大的", "partOfSpeech": "adj.", "example": "The project requires enormous resources.", "exampleTranslation": "该项目需要巨大的资源。", "difficulty": 2},
    {"word": "ensure", "phonetic": "/ɪnˈʃʊr/", "definition": "确保；保证", "partOfSpeech": "v.", "example": "We must ensure quality standards.", "exampleTranslation": "我们必须确保质量标准。", "difficulty": 2},
    {"word": "entity", "phonetic": "/ˈentəti/", "definition": "实体；存在", "partOfSpeech": "n.", "example": "The corporation is a legal entity.", "exampleTranslation": "公司是法人实体。", "difficulty": 5},
    {"word": "environment", "phonetic": "/ɪnˈvaɪrənmənt/", "definition": "环境", "partOfSpeech": "n.", "example": "We must protect the environment.", "exampleTranslation": "我们必须保护环境。", "difficulty": 2},
]

def main():
    import os
    dir_path = os.path.dirname(os.path.abspath(__file__))
    chunk_size = 200
    for i in range(0, len(WORDS), chunk_size):
        chunk = WORDS[i:i + chunk_size]
        file_num = (i // chunk_size) + 1
        filepath = os.path.join(dir_path, f"words-{file_num:03d}.json")
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(chunk, f, ensure_ascii=False, indent=2)
        print(f"Wrote {filepath} with {len(chunk)} words")

if __name__ == "__main__":
    main()
