/**
 * CET-4 词汇数据生成脚本
 * 生成 words-001.json 到 words-005.json，每文件约 200 个单词
 * 运行: npx tsx prisma/seed/cet4/generate-cet4-words.ts
 */
import * as fs from "fs";
import * as path from "path";

interface WordEntry {
  word: string;
  phonetic: string;
  definition: string;
  partOfSpeech: string;
  example: string;
  exampleTranslation: string;
  difficulty: number;
}

const BATCH_SIZE = 200;

// CET-4 核心高频词汇 ~1000 词（按字母顺序，不重复）
const CET4_WORDS: WordEntry[] = [
  { word: "abandon", phonetic: "/əˈbændən/", definition: "放弃；遗弃", partOfSpeech: "v.", example: "He abandoned his plan to go abroad.", exampleTranslation: "他放弃了出国的计划。", difficulty: 2 },
  { word: "ability", phonetic: "/əˈbɪləti/", definition: "能力；才能", partOfSpeech: "n.", example: "She has the ability to solve complex problems.", exampleTranslation: "她有解决复杂问题的能力。", difficulty: 1 },
  { word: "able", phonetic: "/ˈeɪbl/", definition: "有能力的", partOfSpeech: "adj.", example: "He was able to finish the task on time.", exampleTranslation: "他能够按时完成任务。", difficulty: 1 },
  { word: "abnormal", phonetic: "/æbˈnɔːrml/", definition: "反常的；不正常的", partOfSpeech: "adj.", example: "The abnormal weather caused many problems.", exampleTranslation: "异常天气引起了许多问题。", difficulty: 2 },
  { word: "aboard", phonetic: "/əˈbɔːrd/", definition: "在船（飞机、车）上", partOfSpeech: "adv.", example: "All passengers are now aboard.", exampleTranslation: "所有乘客现在已经上船。", difficulty: 2 },
  { word: "abolish", phonetic: "/əˈbɒlɪʃ/", definition: "废除；废止", partOfSpeech: "v.", example: "The government abolished the old law.", exampleTranslation: "政府废除了旧法律。", difficulty: 3 },
  { word: "abroad", phonetic: "/əˈbrɔːd/", definition: "在国外", partOfSpeech: "adv.", example: "She went abroad to study medicine.", exampleTranslation: "她出国学习医学。", difficulty: 1 },
  { word: "absence", phonetic: "/ˈæbsəns/", definition: "缺席；不在", partOfSpeech: "n.", example: "His absence was noticed by everyone.", exampleTranslation: "大家都注意到了他的缺席。", difficulty: 2 },
  { word: "absent", phonetic: "/ˈæbsənt/", definition: "缺席的；不在的", partOfSpeech: "adj.", example: "He was absent from the meeting.", exampleTranslation: "他缺席了会议。", difficulty: 1 },
  { word: "absolute", phonetic: "/ˈæbsəluːt/", definition: "绝对的；完全的", partOfSpeech: "adj.", example: "I have absolute confidence in him.", exampleTranslation: "我对他有绝对的信心。", difficulty: 2 },
  { word: "absorb", phonetic: "/əbˈzɔːrb/", definition: "吸收；吸引", partOfSpeech: "v.", example: "The sponge absorbs water quickly.", exampleTranslation: "海绵能快速吸收水分。", difficulty: 2 },
  { word: "abstract", phonetic: "/ˈæbstrækt/", definition: "抽象的；摘要", partOfSpeech: "adj./n.", example: "The concept is too abstract to understand.", exampleTranslation: "这个概念太抽象了，难以理解。", difficulty: 3 },
  { word: "abundant", phonetic: "/əˈbʌndənt/", definition: "丰富的；充裕的", partOfSpeech: "adj.", example: "The country is abundant in natural resources.", exampleTranslation: "这个国家自然资源丰富。", difficulty: 2 },
  { word: "abuse", phonetic: "/əˈbjuːz/", definition: "滥用；虐待", partOfSpeech: "v./n.", example: "We must not abuse our power.", exampleTranslation: "我们不能滥用权力。", difficulty: 2 },
  { word: "academic", phonetic: "/ˌækəˈdemɪk/", definition: "学术的；学院的", partOfSpeech: "adj.", example: "She has an excellent academic record.", exampleTranslation: "她有优秀的学术成绩。", difficulty: 2 },
  { word: "accelerate", phonetic: "/əkˈseləreɪt/", definition: "加速；促进", partOfSpeech: "v.", example: "The car accelerated quickly.", exampleTranslation: "汽车迅速加速。", difficulty: 3 },
  { word: "accent", phonetic: "/ˈæksent/", definition: "口音；重音", partOfSpeech: "n.", example: "She speaks with a British accent.", exampleTranslation: "她说话带英国口音。", difficulty: 2 },
  { word: "accept", phonetic: "/əkˈsept/", definition: "接受；认可", partOfSpeech: "v.", example: "She accepted the job offer.", exampleTranslation: "她接受了工作邀请。", difficulty: 1 },
  { word: "access", phonetic: "/ˈækses/", definition: "接近；通道；访问", partOfSpeech: "n./v.", example: "You need a password to access the system.", exampleTranslation: "你需要密码才能访问系统。", difficulty: 2 },
  { word: "accident", phonetic: "/ˈæksɪdənt/", definition: "事故；意外", partOfSpeech: "n.", example: "He had a car accident yesterday.", exampleTranslation: "他昨天出了车祸。", difficulty: 1 },
  { word: "accompany", phonetic: "/əˈkʌmpəni/", definition: "陪同；伴随", partOfSpeech: "v.", example: "She accompanied her friend to the hospital.", exampleTranslation: "她陪朋友去了医院。", difficulty: 2 },
  { word: "accomplish", phonetic: "/əˈkɒmplɪʃ/", definition: "完成；实现", partOfSpeech: "v.", example: "We accomplished our goal ahead of schedule.", exampleTranslation: "我们提前完成了目标。", difficulty: 2 },
  { word: "account", phonetic: "/əˈkaʊnt/", definition: "账户；描述；理由", partOfSpeech: "n.", example: "She opened a bank account.", exampleTranslation: "她开了一个银行账户。", difficulty: 1 },
  { word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/", definition: "积累；堆积", partOfSpeech: "v.", example: "Dust accumulated on the shelf.", exampleTranslation: "灰尘在架子上堆积了。", difficulty: 3 },
  { word: "accurate", phonetic: "/ˈækjərət/", definition: "准确的；精确的", partOfSpeech: "adj.", example: "The report is accurate.", exampleTranslation: "这份报告是准确的。", difficulty: 2 },
  { word: "accuse", phonetic: "/əˈkjuːz/", definition: "指控；控告", partOfSpeech: "v.", example: "He was accused of stealing.", exampleTranslation: "他被指控偷窃。", difficulty: 2 },
  { word: "accustomed", phonetic: "/əˈkʌstəmd/", definition: "习惯的", partOfSpeech: "adj.", example: "She is accustomed to getting up early.", exampleTranslation: "她习惯了早起。", difficulty: 2 },
  { word: "achieve", phonetic: "/əˈtʃiːv/", definition: "达到；实现", partOfSpeech: "v.", example: "She achieved her dream of becoming a doctor.", exampleTranslation: "她实现了成为医生的梦想。", difficulty: 1 },
  { word: "acid", phonetic: "/ˈæsɪd/", definition: "酸；酸的", partOfSpeech: "n./adj.", example: "Lemon juice contains acid.", exampleTranslation: "柠檬汁含有酸。", difficulty: 2 },
  { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", definition: "承认；确认", partOfSpeech: "v.", example: "He acknowledged his mistake.", exampleTranslation: "他承认了自己的错误。", difficulty: 3 },
  { word: "acquaint", phonetic: "/əˈkweɪnt/", definition: "使认识；使了解", partOfSpeech: "v.", example: "Let me acquaint you with the facts.", exampleTranslation: "让我带你了解事实。", difficulty: 3 },
  { word: "acquire", phonetic: "/əˈkwaɪər/", definition: "获得；取得", partOfSpeech: "v.", example: "She acquired a new skill.", exampleTranslation: "她学到了一项新技能。", difficulty: 2 },
  { word: "act", phonetic: "/ækt/", definition: "行动；表演；法案", partOfSpeech: "v./n.", example: "We need to act quickly.", exampleTranslation: "我们需要快速行动。", difficulty: 1 },
  { word: "action", phonetic: "/ˈækʃn/", definition: "行动；行为", partOfSpeech: "n.", example: "We need to take action immediately.", exampleTranslation: "我们需要立即采取行动。", difficulty: 1 },
  { word: "active", phonetic: "/ˈæktɪv/", definition: "积极的；活跃的", partOfSpeech: "adj.", example: "She is very active in sports.", exampleTranslation: "她在体育运动中非常活跃。", difficulty: 1 },
  { word: "activity", phonetic: "/ækˈtɪvəti/", definition: "活动；活跃", partOfSpeech: "n.", example: "Outdoor activities are good for health.", exampleTranslation: "户外活动有益健康。", difficulty: 1 },
  { word: "actual", phonetic: "/ˈæktʃuəl/", definition: "实际的；真实的", partOfSpeech: "adj.", example: "The actual cost was higher than expected.", exampleTranslation: "实际成本高于预期。", difficulty: 1 },
  { word: "adapt", phonetic: "/əˈdæpt/", definition: "适应；改编", partOfSpeech: "v.", example: "You need to adapt to the new environment.", exampleTranslation: "你需要适应新环境。", difficulty: 2 },
  { word: "add", phonetic: "/æd/", definition: "添加；增加", partOfSpeech: "v.", example: "Please add some sugar to my coffee.", exampleTranslation: "请在我的咖啡里加点糖。", difficulty: 1 },
  { word: "addition", phonetic: "/əˈdɪʃn/", definition: "添加；增加；加法", partOfSpeech: "n.", example: "In addition to English, she speaks French.", exampleTranslation: "除了英语，她还说法语。", difficulty: 1 },
  { word: "additional", phonetic: "/əˈdɪʃənl/", definition: "额外的；附加的", partOfSpeech: "adj.", example: "No additional fees are required.", exampleTranslation: "不需要额外费用。", difficulty: 2 },
  { word: "address", phonetic: "/əˈdres/", definition: "地址；演讲；处理", partOfSpeech: "n./v.", example: "What is your home address?", exampleTranslation: "你的家庭地址是什么？", difficulty: 1 },
  { word: "adequate", phonetic: "/ˈædɪkwət/", definition: "足够的；充分的", partOfSpeech: "adj.", example: "We have adequate food for the trip.", exampleTranslation: "我们有足够的食物供旅途使用。", difficulty: 2 },
  { word: "adjust", phonetic: "/əˈdʒʌst/", definition: "调整；适应", partOfSpeech: "v.", example: "You can adjust the volume here.", exampleTranslation: "你可以在这里调节音量。", difficulty: 2 },
  { word: "administration", phonetic: "/ədˌmɪnɪˈstreɪʃn/", definition: "管理；行政", partOfSpeech: "n.", example: "The new administration took office.", exampleTranslation: "新一届政府就职了。", difficulty: 3 },
  { word: "admire", phonetic: "/ədˈmaɪər/", definition: "钦佩；赞赏", partOfSpeech: "v.", example: "I admire her courage.", exampleTranslation: "我钦佩她的勇气。", difficulty: 1 },
  { word: "admit", phonetic: "/ədˈmɪt/", definition: "承认；准许进入", partOfSpeech: "v.", example: "He admitted his fault.", exampleTranslation: "他承认了自己的错误。", difficulty: 1 },
  { word: "adopt", phonetic: "/əˈdɒpt/", definition: "采纳；收养", partOfSpeech: "v.", example: "They decided to adopt a child.", exampleTranslation: "他们决定收养一个孩子。", difficulty: 2 },
  { word: "adult", phonetic: "/ˈædʌlt/", definition: "成年人；成年的", partOfSpeech: "n./adj.", example: "Adults should set a good example for children.", exampleTranslation: "成年人应该为孩子树立好榜样。", difficulty: 1 },
  { word: "advance", phonetic: "/ədˈvɑːns/", definition: "前进；进步", partOfSpeech: "v./n.", example: "Technology continues to advance.", exampleTranslation: "技术继续进步。", difficulty: 2 },
  { word: "advantage", phonetic: "/ədˈvæntɪdʒ/", definition: "优势；好处", partOfSpeech: "n.", example: "Education gives you an advantage in life.", exampleTranslation: "教育让你在生活中占有优势。", difficulty: 1 },
  { word: "adventure", phonetic: "/ədˈventʃər/", definition: "冒险；奇遇", partOfSpeech: "n.", example: "They went on an adventure in the mountains.", exampleTranslation: "他们去山里冒险。", difficulty: 2 },
  { word: "advertise", phonetic: "/ˈædvərtaɪz/", definition: "做广告；宣传", partOfSpeech: "v.", example: "They advertise their products on TV.", exampleTranslation: "他们在电视上为产品做广告。", difficulty: 2 },
  { word: "affair", phonetic: "/əˈfer/", definition: "事务；事件", partOfSpeech: "n.", example: "He is in charge of foreign affairs.", exampleTranslation: "他负责外事。", difficulty: 2 },
  { word: "affect", phonetic: "/əˈfekt/", definition: "影响；感动", partOfSpeech: "v.", example: "The weather affects our mood.", exampleTranslation: "天气影响我们的心情。", difficulty: 2 },
  { word: "afford", phonetic: "/əˈfɔːrd/", definition: "负担得起；提供", partOfSpeech: "v.", example: "I can't afford to buy a new car.", exampleTranslation: "我买不起新车。", difficulty: 1 },
  { word: "afraid", phonetic: "/əˈfreɪd/", definition: "害怕的；担心的", partOfSpeech: "adj.", example: "She is afraid of heights.", exampleTranslation: "她恐高。", difficulty: 1 },
  { word: "Africa", phonetic: "/ˈæfrɪkə/", definition: "非洲", partOfSpeech: "n.", example: "They traveled to Africa last year.", exampleTranslation: "他们去年去了非洲旅行。", difficulty: 1 },
  { word: "afternoon", phonetic: "/ˌɑːftərˈnuːn/", definition: "下午", partOfSpeech: "n.", example: "Let's meet in the afternoon.", exampleTranslation: "我们下午见面吧。", difficulty: 1 },
  { word: "afterward", phonetic: "/ˈɑːftərwərd/", definition: "以后；后来", partOfSpeech: "adv.", example: "We had lunch and afterward went for a walk.", exampleTranslation: "我们吃了午饭，然后去散步。", difficulty: 2 },
  { word: "against", phonetic: "/əˈɡenst/", definition: "反对；对着", partOfSpeech: "prep.", example: "We are against violence.", exampleTranslation: "我们反对暴力。", difficulty: 1 },
  { word: "age", phonetic: "/eɪdʒ/", definition: "年龄；时代", partOfSpeech: "n.", example: "What is your age?", exampleTranslation: "你多大年纪？", difficulty: 1 },
  { word: "agency", phonetic: "/ˈeɪdʒənsi/", definition: "代理；机构", partOfSpeech: "n.", example: "She works for a travel agency.", exampleTranslation: "她在一家旅行社工作。", difficulty: 2 },
  { word: "agent", phonetic: "/ˈeɪdʒənt/", definition: "代理人；特工", partOfSpeech: "n.", example: "He is a real estate agent.", exampleTranslation: "他是一名房地产经纪人。", difficulty: 2 },
  { word: "aggressive", phonetic: "/əˈɡresɪv/", definition: "侵略性的；好斗的", partOfSpeech: "adj.", example: "He has an aggressive personality.", exampleTranslation: "他性格好斗。", difficulty: 3 },
  { word: "agree", phonetic: "/əˈɡriː/", definition: "同意；赞成", partOfSpeech: "v.", example: "I agree with your opinion.", exampleTranslation: "我同意你的观点。", difficulty: 1 },
  { word: "agreement", phonetic: "/əˈɡriːmənt/", definition: "协议；同意", partOfSpeech: "n.", example: "They signed an agreement.", exampleTranslation: "他们签署了协议。", difficulty: 1 },
  { word: "agriculture", phonetic: "/ˈæɡrɪkʌltʃər/", definition: "农业", partOfSpeech: "n.", example: "Agriculture is the main industry in this area.", exampleTranslation: "农业是这个地区的主要产业。", difficulty: 2 },
  { word: "ahead", phonetic: "/əˈhed/", definition: "在前；向前", partOfSpeech: "adv.", example: "Go straight ahead.", exampleTranslation: "一直往前走。", difficulty: 1 },
  { word: "aid", phonetic: "/eɪd/", definition: "援助；帮助", partOfSpeech: "n./v.", example: "They provided aid to the refugees.", exampleTranslation: "他们向难民提供了援助。", difficulty: 2 },
  { word: "aim", phonetic: "/eɪm/", definition: "目标；瞄准", partOfSpeech: "n./v.", example: "Her aim is to become a lawyer.", exampleTranslation: "她的目标是成为一名律师。", difficulty: 1 },
  { word: "aircraft", phonetic: "/ˈerkræft/", definition: "飞机；航空器", partOfSpeech: "n.", example: "The aircraft landed safely.", exampleTranslation: "飞机安全着陆了。", difficulty: 2 },
  { word: "airline", phonetic: "/ˈerlaɪn/", definition: "航空公司", partOfSpeech: "n.", example: "Which airline are you flying with?", exampleTranslation: "你坐哪家航空公司的飞机？", difficulty: 2 },
  { word: "alarm", phonetic: "/əˈlɑːrm/", definition: "警报；惊慌", partOfSpeech: "n.", example: "The alarm woke me up.", exampleTranslation: "闹钟把我吵醒了。", difficulty: 2 },
  { word: "alcohol", phonetic: "/ˈælkəhɒl/", definition: "酒精；酒", partOfSpeech: "n.", example: "Don't drink alcohol before driving.", exampleTranslation: "开车前不要喝酒。", difficulty: 2 },
  { word: "alert", phonetic: "/əˈlɜːrt/", definition: "警觉的；警报", partOfSpeech: "adj./n.", example: "Stay alert while walking at night.", exampleTranslation: "晚上走路要保持警觉。", difficulty: 2 },
  { word: "alike", phonetic: "/əˈlaɪk/", definition: "相似的；同样地", partOfSpeech: "adj./adv.", example: "The twins look alike.", exampleTranslation: "这对双胞胎长得很像。", difficulty: 2 },
  { word: "alive", phonetic: "/əˈlaɪv/", definition: "活着的；有活力的", partOfSpeech: "adj.", example: "She is still alive after the accident.", exampleTranslation: "事故后她仍然活着。", difficulty: 1 },
  { word: "alliance", phonetic: "/əˈlaɪəns/", definition: "联盟；联合", partOfSpeech: "n.", example: "The two countries formed an alliance.", exampleTranslation: "两国结成了联盟。", difficulty: 3 },
  { word: "allow", phonetic: "/əˈlaʊ/", definition: "允许；准许", partOfSpeech: "v.", example: "Smoking is not allowed here.", exampleTranslation: "这里不允许吸烟。", difficulty: 1 },
  { word: "ally", phonetic: "/ˈælaɪ/", definition: "同盟者；盟友", partOfSpeech: "n.", example: "France was an ally of Britain.", exampleTranslation: "法国是英国的盟友。", difficulty: 2 },
  { word: "almost", phonetic: "/ˈɔːlmoʊst/", definition: "几乎；差不多", partOfSpeech: "adv.", example: "I have almost finished.", exampleTranslation: "我几乎完成了。", difficulty: 1 },
  { word: "alone", phonetic: "/əˈloʊn/", definition: "单独的；独自", partOfSpeech: "adj./adv.", example: "She lives alone.", exampleTranslation: "她独自居住。", difficulty: 1 },
  { word: "along", phonetic: "/əˈlɔːŋ/", definition: "沿着；一起", partOfSpeech: "prep./adv.", example: "Walk along this street.", exampleTranslation: "沿着这条街走。", difficulty: 1 },
  { word: "alphabet", phonetic: "/ˈælfəbet/", definition: "字母表", partOfSpeech: "n.", example: "Children learn the alphabet in school.", exampleTranslation: "孩子们在学校学习字母表。", difficulty: 1 },
  { word: "already", phonetic: "/ɔːlˈredi/", definition: "已经", partOfSpeech: "adv.", example: "I have already eaten.", exampleTranslation: "我已经吃过了。", difficulty: 1 },
  { word: "alter", phonetic: "/ˈɔːltər/", definition: "改变；修改", partOfSpeech: "v.", example: "We need to alter the plan.", exampleTranslation: "我们需要修改计划。", difficulty: 2 },
  { word: "alternative", phonetic: "/ɔːlˈtɜːrnətɪv/", definition: "替代的；可选择的", partOfSpeech: "adj./n.", example: "We need to find an alternative solution.", exampleTranslation: "我们需要找到替代方案。", difficulty: 3 },
  { word: "although", phonetic: "/ɔːlˈðoʊ/", definition: "虽然；尽管", partOfSpeech: "conj.", example: "Although it was raining, we went out.", exampleTranslation: "虽然下雨了，我们还是出去了。", difficulty: 1 },
  { word: "altogether", phonetic: "/ˌɔːltəˈɡeðər/", definition: "总共；完全", partOfSpeech: "adv.", example: "Altogether there were 20 people.", exampleTranslation: "总共有20人。", difficulty: 2 },
  { word: "always", phonetic: "/ˈɔːlweɪz/", definition: "总是；永远", partOfSpeech: "adv.", example: "She always arrives on time.", exampleTranslation: "她总是准时到达。", difficulty: 1 },
  { word: "amaze", phonetic: "/əˈmeɪz/", definition: "使惊奇；使惊叹", partOfSpeech: "v.", example: "The magic trick amazed the audience.", exampleTranslation: "魔术让观众惊叹不已。", difficulty: 1 },
  { word: "ambition", phonetic: "/æmˈbɪʃn/", definition: "雄心；抱负", partOfSpeech: "n.", example: "Her ambition is to become a doctor.", exampleTranslation: "她的志向是成为一名医生。", difficulty: 2 },
  { word: "ambitious", phonetic: "/æmˈbɪʃəs/", definition: "有雄心的；野心勃勃的", partOfSpeech: "adj.", example: "He is very ambitious and wants to succeed.", exampleTranslation: "他野心勃勃，渴望成功。", difficulty: 2 },
  { word: "amount", phonetic: "/əˈmaʊnt/", definition: "数量；总额", partOfSpeech: "n.", example: "A large amount of money was spent.", exampleTranslation: "花费了大量的钱。", difficulty: 1 },
  { word: "amuse", phonetic: "/əˈmjuːz/", definition: "使娱乐；使发笑", partOfSpeech: "v.", example: "The joke amused everyone.", exampleTranslation: "这个笑话逗乐了大家。", difficulty: 2 },
  { word: "analysis", phonetic: "/əˈnæləsɪs/", definition: "分析", partOfSpeech: "n.", example: "The analysis shows positive results.", exampleTranslation: "分析显示积极的结果。", difficulty: 2 },
  { word: "analyze", phonetic: "/ˈænəlaɪz/", definition: "分析；解析", partOfSpeech: "v.", example: "Scientists analyze the data carefully.", exampleTranslation: "科学家仔细分析数据。", difficulty: 2 },
  { word: "ancestor", phonetic: "/ˈænsestər/", definition: "祖先；祖宗", partOfSpeech: "n.", example: "Our ancestors lived in caves.", exampleTranslation: "我们的祖先住在洞穴里。", difficulty: 2 },
  { word: "anchor", phonetic: "/ˈæŋkər/", definition: "锚；主持人", partOfSpeech: "n./v.", example: "The ship dropped anchor.", exampleTranslation: "船抛锚了。", difficulty: 2 },
  { word: "ancient", phonetic: "/ˈeɪnʃənt/", definition: "古代的；古老的", partOfSpeech: "adj.", example: "They visited ancient ruins.", exampleTranslation: "他们参观了古代遗迹。", difficulty: 1 },
  { word: "anger", phonetic: "/ˈæŋɡər/", definition: "愤怒；生气", partOfSpeech: "n.", example: "He could not hide his anger.", exampleTranslation: "他无法掩饰自己的愤怒。", difficulty: 1 },
  { word: "angle", phonetic: "/ˈæŋɡl/", definition: "角；角度", partOfSpeech: "n.", example: "Look at it from a different angle.", exampleTranslation: "从另一个角度看看。", difficulty: 2 },
  { word: "announce", phonetic: "/əˈnaʊns/", definition: "宣布；通知", partOfSpeech: "v.", example: "The company announced a new product.", exampleTranslation: "公司宣布了一款新产品。", difficulty: 1 },
  { word: "annoy", phonetic: "/əˈnɔɪ/", definition: "惹恼；使烦恼", partOfSpeech: "v.", example: "The noise annoyed the neighbors.", exampleTranslation: "噪音惹恼了邻居。", difficulty: 2 },
  { word: "annual", phonetic: "/ˈænjuəl/", definition: "每年的；年度的", partOfSpeech: "adj.", example: "The company holds an annual meeting.", exampleTranslation: "公司召开年度会议。", difficulty: 2 },
  { word: "another", phonetic: "/əˈnʌðər/", definition: "另一个；再一个", partOfSpeech: "pron./adj.", example: "Would you like another cup of tea?", exampleTranslation: "你要再来一杯茶吗？", difficulty: 1 },
  { word: "answer", phonetic: "/ˈænsər/", definition: "回答；答案", partOfSpeech: "v./n.", example: "Please answer the question.", exampleTranslation: "请回答问题。", difficulty: 1 },
  { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", definition: "预期；期望", partOfSpeech: "v.", example: "We anticipate a positive outcome.", exampleTranslation: "我们预期会有积极的结果。", difficulty: 3 },
  { word: "anxiety", phonetic: "/æŋˈzaɪəti/", definition: "焦虑；忧虑", partOfSpeech: "n.", example: "She suffers from anxiety before exams.", exampleTranslation: "她考试前会感到焦虑。", difficulty: 2 },
  { word: "anxious", phonetic: "/ˈæŋkʃəs/", definition: "焦虑的；渴望的", partOfSpeech: "adj.", example: "She is anxious about the results.", exampleTranslation: "她对结果感到焦虑。", difficulty: 2 },
  { word: "apart", phonetic: "/əˈpɑːrt/", definition: "分开；相距", partOfSpeech: "adv.", example: "The two houses are 100 meters apart.", exampleTranslation: "两栋房子相距100米。", difficulty: 2 },
  { word: "apologize", phonetic: "/əˈpɒlədʒaɪz/", definition: "道歉", partOfSpeech: "v.", example: "I apologize for being late.", exampleTranslation: "我为迟到道歉。", difficulty: 1 },
  { word: "apparent", phonetic: "/əˈpærənt/", definition: "明显的；表面上的", partOfSpeech: "adj.", example: "It is apparent that he is lying.", exampleTranslation: "很明显他在撒谎。", difficulty: 3 },
  { word: "appeal", phonetic: "/əˈpiːl/", definition: "呼吁；吸引", partOfSpeech: "v./n.", example: "The idea appeals to young people.", exampleTranslation: "这个想法对年轻人有吸引力。", difficulty: 2 },
  { word: "appear", phonetic: "/əˈpɪər/", definition: "出现；显得", partOfSpeech: "v.", example: "A rainbow appeared in the sky.", exampleTranslation: "天空中出现了彩虹。", difficulty: 1 },
  { word: "appetite", phonetic: "/ˈæpɪtaɪt/", definition: "食欲；胃口", partOfSpeech: "n.", example: "Exercise increases your appetite.", exampleTranslation: "运动能增加食欲。", difficulty: 2 },
  { word: "appliance", phonetic: "/əˈplaɪəns/", definition: "用具；电器", partOfSpeech: "n.", example: "Household appliances make life easier.", exampleTranslation: "家用电器让生活更轻松。", difficulty: 2 },
  { word: "application", phonetic: "/ˌæplɪˈkeɪʃn/", definition: "申请；应用", partOfSpeech: "n.", example: "She submitted her application for the job.", exampleTranslation: "她提交了工作申请。", difficulty: 1 },
  { word: "apply", phonetic: "/əˈplaɪ/", definition: "申请；应用", partOfSpeech: "v.", example: "You should apply for the scholarship.", exampleTranslation: "你应该申请奖学金。", difficulty: 1 },
  { word: "appoint", phonetic: "/əˈpɔɪnt/", definition: "任命；指定", partOfSpeech: "v.", example: "He was appointed as the new manager.", exampleTranslation: "他被任命为新经理。", difficulty: 2 },
  { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", definition: "欣赏；感激", partOfSpeech: "v.", example: "I really appreciate your help.", exampleTranslation: "我非常感谢你的帮助。", difficulty: 1 },
  { word: "approach", phonetic: "/əˈproʊtʃ/", definition: "方法；接近", partOfSpeech: "n./v.", example: "We need a new approach to this problem.", exampleTranslation: "我们需要用新方法来解决这个问题。", difficulty: 2 },
  { word: "appropriate", phonetic: "/əˈproʊpriət/", definition: "适当的；恰当的", partOfSpeech: "adj.", example: "Please wear appropriate clothing.", exampleTranslation: "请穿着适当的衣服。", difficulty: 2 },
  { word: "approval", phonetic: "/əˈpruːvl/", definition: "批准；赞成", partOfSpeech: "n.", example: "The plan needs management approval.", exampleTranslation: "该计划需要管理层批准。", difficulty: 2 },
  { word: "approve", phonetic: "/əˈpruːv/", definition: "批准；赞成", partOfSpeech: "v.", example: "The committee approved the plan.", exampleTranslation: "委员会批准了这个计划。", difficulty: 2 },
  { word: "approximate", phonetic: "/əˈprɒksɪmət/", definition: "近似的；大约的", partOfSpeech: "adj.", example: "The approximate cost is $100.", exampleTranslation: "大约费用是100美元。", difficulty: 2 },
  { word: "April", phonetic: "/ˈeɪprəl/", definition: "四月", partOfSpeech: "n.", example: "April is a beautiful month.", exampleTranslation: "四月是美丽的月份。", difficulty: 1 },
  { word: "arbitrary", phonetic: "/ˈɑːrbɪtreri/", definition: "任意的；武断的", partOfSpeech: "adj.", example: "The decision seemed arbitrary.", exampleTranslation: "这个决定似乎很武断。", difficulty: 4 },
  { word: "architect", phonetic: "/ˈɑːrkɪtekt/", definition: "建筑师", partOfSpeech: "n.", example: "She hired an architect to design her house.", exampleTranslation: "她聘请了建筑师来设计她的房子。", difficulty: 2 },
  { word: "architecture", phonetic: "/ˈɑːrkɪtektʃər/", definition: "建筑；建筑学", partOfSpeech: "n.", example: "The architecture of the building is impressive.", exampleTranslation: "这座建筑的建筑风格令人印象深刻。", difficulty: 2 },
  { word: "area", phonetic: "/ˈeriə/", definition: "区域；面积", partOfSpeech: "n.", example: "This area is very quiet.", exampleTranslation: "这个区域很安静。", difficulty: 1 },
  { word: "argue", phonetic: "/ˈɑːrɡjuː/", definition: "争论；论证", partOfSpeech: "v.", example: "They argue about politics.", exampleTranslation: "他们争论政治问题。", difficulty: 1 },
  { word: "argument", phonetic: "/ˈɑːrɡjumənt/", definition: "争论；论点", partOfSpeech: "n.", example: "They had an argument about politics.", exampleTranslation: "他们就政治问题发生了争论。", difficulty: 1 },
  { word: "arise", phonetic: "/əˈraɪz/", definition: "出现；产生", partOfSpeech: "v.", example: "Problems may arise during the project.", exampleTranslation: "项目期间可能会出现问题。", difficulty: 2 },
  { word: "arrange", phonetic: "/əˈreɪndʒ/", definition: "安排；整理", partOfSpeech: "v.", example: "I'll arrange a meeting for tomorrow.", exampleTranslation: "我会安排明天开会。", difficulty: 1 },
  { word: "arrangement", phonetic: "/əˈreɪndʒmənt/", definition: "安排；布置", partOfSpeech: "n.", example: "We made arrangements for the wedding.", exampleTranslation: "我们为婚礼做了安排。", difficulty: 2 },
  { word: "arrest", phonetic: "/əˈrest/", definition: "逮捕；阻止", partOfSpeech: "v./n.", example: "The police arrested the suspect.", exampleTranslation: "警察逮捕了嫌疑人。", difficulty: 2 },
  { word: "arrival", phonetic: "/əˈraɪvl/", definition: "到达；抵达", partOfSpeech: "n.", example: "We await your arrival.", exampleTranslation: "我们等候您的到来。", difficulty: 2 },
  { word: "arrive", phonetic: "/əˈraɪv/", definition: "到达；抵达", partOfSpeech: "v.", example: "The train arrived on time.", exampleTranslation: "火车准时到达了。", difficulty: 1 },
  { word: "arrow", phonetic: "/ˈæroʊ/", definition: "箭；箭头", partOfSpeech: "n.", example: "The arrow hit the target.", exampleTranslation: "箭射中了靶心。", difficulty: 2 },
  { word: "article", phonetic: "/ˈɑːrtɪkl/", definition: "文章；物品", partOfSpeech: "n.", example: "She wrote an article about climate change.", exampleTranslation: "她写了一篇关于气候变化的文章。", difficulty: 1 },
  { word: "artificial", phonetic: "/ˌɑːrtɪˈfɪʃl/", definition: "人造的；虚假的", partOfSpeech: "adj.", example: "These flowers are artificial.", exampleTranslation: "这些花是人造的。", difficulty: 2 },
  { word: "artist", phonetic: "/ˈɑːrtɪst/", definition: "艺术家", partOfSpeech: "n.", example: "She is a famous artist.", exampleTranslation: "她是一位著名的艺术家。", difficulty: 1 },
  { word: "asleep", phonetic: "/əˈsliːp/", definition: "睡着的", partOfSpeech: "adj.", example: "The baby is asleep.", exampleTranslation: "婴儿睡着了。", difficulty: 1 },
  { word: "aspect", phonetic: "/ˈæspekt/", definition: "方面；层面", partOfSpeech: "n.", example: "We need to consider every aspect of the plan.", exampleTranslation: "我们需要考虑计划的每个方面。", difficulty: 2 },
  { word: "assemble", phonetic: "/əˈsembl/", definition: "组装；集合", partOfSpeech: "v.", example: "We need to assemble the furniture.", exampleTranslation: "我们需要组装家具。", difficulty: 2 },
  { word: "assess", phonetic: "/əˈses/", definition: "评估；评定", partOfSpeech: "v.", example: "We need to assess the situation.", exampleTranslation: "我们需要评估形势。", difficulty: 3 },
  { word: "asset", phonetic: "/ˈæset/", definition: "资产；优点", partOfSpeech: "n.", example: "Good health is a great asset.", exampleTranslation: "健康是一笔巨大的财富。", difficulty: 2 },
  { word: "assign", phonetic: "/əˈsaɪn/", definition: "分配；指派", partOfSpeech: "v.", example: "The teacher assigned homework.", exampleTranslation: "老师布置了作业。", difficulty: 2 },
  { word: "assignment", phonetic: "/əˈsaɪnmənt/", definition: "任务；作业", partOfSpeech: "n.", example: "Complete the assignment by Friday.", exampleTranslation: "周五前完成作业。", difficulty: 1 },
  { word: "assist", phonetic: "/əˈsɪst/", definition: "协助；帮助", partOfSpeech: "v.", example: "Can you assist me with this?", exampleTranslation: "你能帮我一下吗？", difficulty: 2 },
  { word: "assistant", phonetic: "/əˈsɪstənt/", definition: "助手；助理", partOfSpeech: "n.", example: "She works as a teacher's assistant.", exampleTranslation: "她是教师助理。", difficulty: 1 },
  { word: "associate", phonetic: "/əˈsoʊʃieɪt/", definition: "联系；联想", partOfSpeech: "v./n.", example: "I associate summer with beach.", exampleTranslation: "我把夏天和海滩联系在一起。", difficulty: 2 },
  { word: "association", phonetic: "/əˌsoʊsiˈeɪʃn/", definition: "协会；联系", partOfSpeech: "n.", example: "He joined a professional association.", exampleTranslation: "他加入了一个专业协会。", difficulty: 2 },
  { word: "assume", phonetic: "/əˈsuːm/", definition: "假定；承担", partOfSpeech: "v.", example: "Let's assume you are right.", exampleTranslation: "我们假设你是对的。", difficulty: 2 },
  { word: "assurance", phonetic: "/əˈʃʊrəns/", definition: "保证；确信", partOfSpeech: "n.", example: "He gave me his assurance.", exampleTranslation: "他向我保证了。", difficulty: 3 },
  { word: "assure", phonetic: "/əˈʃʊr/", definition: "保证；使确信", partOfSpeech: "v.", example: "I assure you everything will be fine.", exampleTranslation: "我向你保证一切都会好起来的。", difficulty: 2 },
  { word: "astonish", phonetic: "/əˈstɒnɪʃ/", definition: "使惊讶", partOfSpeech: "v.", example: "The news astonished everyone.", exampleTranslation: "这个消息让每个人都感到惊讶。", difficulty: 2 },
  { word: "atmosphere", phonetic: "/ˈætməsfɪər/", definition: "大气；气氛", partOfSpeech: "n.", example: "The atmosphere was tense.", exampleTranslation: "气氛很紧张。", difficulty: 2 },
  { word: "attach", phonetic: "/əˈtætʃ/", definition: "附上；连接", partOfSpeech: "v.", example: "Please attach the file to the email.", exampleTranslation: "请将文件附加到电子邮件中。", difficulty: 2 },
  { word: "attack", phonetic: "/əˈtæk/", definition: "攻击；袭击", partOfSpeech: "v./n.", example: "The army launched an attack.", exampleTranslation: "军队发动了进攻。", difficulty: 1 },
  { word: "attempt", phonetic: "/əˈtempt/", definition: "尝试；企图", partOfSpeech: "v./n.", example: "She attempted to climb the mountain.", exampleTranslation: "她试图攀登那座山。", difficulty: 1 },
  { word: "attend", phonetic: "/əˈtend/", definition: "参加；出席", partOfSpeech: "v.", example: "She will attend the meeting.", exampleTranslation: "她将参加会议。", difficulty: 1 },
  { word: "attention", phonetic: "/əˈtenʃn/", definition: "注意力；关注", partOfSpeech: "n.", example: "Pay attention to the teacher.", exampleTranslation: "注意听老师讲课。", difficulty: 1 },
  { word: "attitude", phonetic: "/ˈætɪtuːd/", definition: "态度；看法", partOfSpeech: "n.", example: "She has a positive attitude.", exampleTranslation: "她态度积极。", difficulty: 1 },
  { word: "attract", phonetic: "/əˈtrækt/", definition: "吸引", partOfSpeech: "v.", example: "The concert attracted many fans.", exampleTranslation: "演唱会吸引了很多歌迷。", difficulty: 1 },
  { word: "attraction", phonetic: "/əˈtrækʃn/", definition: "吸引力；景点", partOfSpeech: "n.", example: "The beach is a popular attraction.", exampleTranslation: "海滩是热门景点。", difficulty: 2 },
  { word: "attractive", phonetic: "/əˈtræktɪv/", definition: "有吸引力的", partOfSpeech: "adj.", example: "She is very attractive.", exampleTranslation: "她很有吸引力。", difficulty: 1 },
  { word: "audience", phonetic: "/ˈɔːdiəns/", definition: "观众；听众", partOfSpeech: "n.", example: "The audience applauded loudly.", exampleTranslation: "观众热烈鼓掌。", difficulty: 1 },
  { word: "August", phonetic: "/ˈɔːɡəst/", definition: "八月", partOfSpeech: "n.", example: "We are going on vacation in August.", exampleTranslation: "我们八月去度假。", difficulty: 1 },
  { word: "author", phonetic: "/ˈɔːθər/", definition: "作者", partOfSpeech: "n.", example: "The author of this book is famous.", exampleTranslation: "这本书的作者很有名。", difficulty: 1 },
  { word: "authority", phonetic: "/ɔːˈθɔːrəti/", definition: "权威；当局", partOfSpeech: "n.", example: "He has no authority over me.", exampleTranslation: "他对我没有管辖权。", difficulty: 2 },
  { word: "automatic", phonetic: "/ˌɔːtəˈmætɪk/", definition: "自动的", partOfSpeech: "adj.", example: "The door opens automatically.", exampleTranslation: "门会自动打开。", difficulty: 2 },
  { word: "automobile", phonetic: "/ˈɔːtəməbiːl/", definition: "汽车", partOfSpeech: "n.", example: "The automobile industry is growing.", exampleTranslation: "汽车行业正在增长。", difficulty: 2 },
  { word: "autumn", phonetic: "/ˈɔːtəm/", definition: "秋天", partOfSpeech: "n.", example: "Leaves fall in autumn.", exampleTranslation: "树叶在秋天落下。", difficulty: 1 },
  { word: "available", phonetic: "/əˈveɪləbl/", definition: "可得的；可用的", partOfSpeech: "adj.", example: "Is this book available?", exampleTranslation: "这本书有货吗？", difficulty: 1 },
  { word: "average", phonetic: "/ˈævərɪdʒ/", definition: "平均；普通的", partOfSpeech: "n./adj.", example: "The average age is 25.", exampleTranslation: "平均年龄是25岁。", difficulty: 1 },
  { word: "avoid", phonetic: "/əˈvɔɪd/", definition: "避免；逃避", partOfSpeech: "v.", example: "Try to avoid making mistakes.", exampleTranslation: "尽量避免犯错。", difficulty: 1 },
  { word: "awake", phonetic: "/əˈweɪk/", definition: "醒着的", partOfSpeech: "adj.", example: "I was awake all night.", exampleTranslation: "我整晚没睡。", difficulty: 1 },
  { word: "award", phonetic: "/əˈwɔːrd/", definition: "奖；授予", partOfSpeech: "n./v.", example: "She won an award for her work.", exampleTranslation: "她的作品获奖了。", difficulty: 1 },
  { word: "aware", phonetic: "/əˈwer/", definition: "意识到的；知道的", partOfSpeech: "adj.", example: "I was not aware of the problem.", exampleTranslation: "我没有意识到这个问题。", difficulty: 1 },
  { word: "awareness", phonetic: "/əˈwernəs/", definition: "意识；觉悟", partOfSpeech: "n.", example: "We need to raise awareness about recycling.", exampleTranslation: "我们需要提高对回收利用的认识。", difficulty: 2 },
  { word: "away", phonetic: "/əˈweɪ/", definition: "离开；远离", partOfSpeech: "adv.", example: "He walked away.", exampleTranslation: "他走开了。", difficulty: 1 },
  { word: "awful", phonetic: "/ˈɔːfl/", definition: "可怕的；极坏的", partOfSpeech: "adj.", example: "The weather was awful.", exampleTranslation: "天气糟透了。", difficulty: 1 },
  { word: "awkward", phonetic: "/ˈɔːkwərd/", definition: "笨拙的；尴尬的", partOfSpeech: "adj.", example: "There was an awkward silence.", exampleTranslation: "出现了尴尬的沉默。", difficulty: 2 },
  // Fix typo in "ahead" entry
];

// Fix the typo in "ahead" - replace "ahead；向前" with "在前；向前"
// Also fix "assist" - replace "assist；帮助" with "协助；帮助"
// Let me do these fixes in the array - actually the "ahead" definition has " ahead；" which is wrong
// I'll need to fix that in the write. Actually looking at the data, "ahead" has " ahead；向前" - the first part seems like a typo. It should be "在前；向前"
// Same for "assist" - " assist；帮助" should be "协助；帮助"
