/**
 * 成就种子数据 - 12 个成就的定义
 * 每个成就有 7 个等级（参考王者荣耀段位体系）
 */

export interface AchievementSeed {
  code: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  bronzeThreshold: number;   // 倔强青铜
  silverThreshold: number;   // 秩序白银
  goldThreshold: number;     // 荣耀黄金
  platinumThreshold: number; // 尊贵铂金
  diamondThreshold: number;  // 永恒钻石
  starThreshold: number;     // 至尊星耀
  kingThreshold: number;     // 最强王者
}

/** 12 个成就定义（7 级阈值） */
export const ACHIEVEMENTS: AchievementSeed[] = [
  {
    code: "vocab_learner",
    name: "词汇新手",
    description: "累计学习单词数量",
    category: "learning",
    icon: "BookOpen",
    bronzeThreshold: 50,
    silverThreshold: 200,
    goldThreshold: 500,
    platinumThreshold: 1000,
    diamondThreshold: 2000,
    starThreshold: 3500,
    kingThreshold: 5000,
  },
  {
    code: "streak_master",
    name: "坚持不懈",
    description: "连续打卡天数",
    category: "streak",
    icon: "Flame",
    bronzeThreshold: 3,
    silverThreshold: 7,
    goldThreshold: 14,
    platinumThreshold: 30,
    diamondThreshold: 60,
    starThreshold: 120,
    kingThreshold: 365,
  },
  {
    code: "review_expert",
    name: "复习达人",
    description: "累计复习次数",
    category: "review",
    icon: "Target",
    bronzeThreshold: 50,
    silverThreshold: 200,
    goldThreshold: 500,
    platinumThreshold: 1000,
    diamondThreshold: 2000,
    starThreshold: 5000,
    kingThreshold: 10000,
  },
  {
    code: "accuracy_star",
    name: "精准射手",
    description: "单次测验正确率",
    category: "accuracy",
    icon: "Award",
    bronzeThreshold: 60,
    silverThreshold: 70,
    goldThreshold: 80,
    platinumThreshold: 85,
    diamondThreshold: 90,
    starThreshold: 95,
    kingThreshold: 100,
  },
  {
    code: "spell_master",
    name: "拼写高手",
    description: "拼写正确的单词数量",
    category: "spelling",
    icon: "PenTool",
    bronzeThreshold: 30,
    silverThreshold: 100,
    goldThreshold: 200,
    platinumThreshold: 500,
    diamondThreshold: 1000,
    starThreshold: 2000,
    kingThreshold: 5000,
  },
  {
    code: "book_conqueror",
    name: "词书征服者",
    description: "完成的词书数量",
    category: "book",
    icon: "Trophy",
    bronzeThreshold: 1,
    silverThreshold: 2,
    goldThreshold: 3,
    platinumThreshold: 5,
    diamondThreshold: 8,
    starThreshold: 12,
    kingThreshold: 20,
  },
  {
    code: "study_timer",
    name: "学习时长",
    description: "累计学习时长（分钟）",
    category: "time",
    icon: "Clock",
    bronzeThreshold: 30,
    silverThreshold: 120,
    goldThreshold: 300,
    platinumThreshold: 600,
    diamondThreshold: 1500,
    starThreshold: 3000,
    kingThreshold: 6000,
  },
  {
    code: "early_bird",
    name: "早起鸟",
    description: "早上 6-8 点学习的次数",
    category: "habit",
    icon: "Sunrise",
    bronzeThreshold: 3,
    silverThreshold: 10,
    goldThreshold: 20,
    platinumThreshold: 50,
    diamondThreshold: 100,
    starThreshold: 200,
    kingThreshold: 365,
  },
  {
    code: "night_owl",
    name: "夜猫子",
    description: "晚上 22-24 点学习的次数",
    category: "challenge",
    icon: "Moon",
    bronzeThreshold: 3,
    silverThreshold: 10,
    goldThreshold: 20,
    platinumThreshold: 50,
    diamondThreshold: 100,
    starThreshold: 200,
    kingThreshold: 365,
  },
  {
    code: "weekend_warrior",
    name: "周末战士",
    description: "周末学习的次数",
    category: "challenge",
    icon: "Calendar",
    bronzeThreshold: 3,
    silverThreshold: 10,
    goldThreshold: 20,
    platinumThreshold: 50,
    diamondThreshold: 100,
    starThreshold: 200,
    kingThreshold: 365,
  },
  {
    code: "word_slayer",
    name: "百词斩",
    description: "单日学习 100 词的天数",
    category: "milestone",
    icon: "Zap",
    bronzeThreshold: 1,
    silverThreshold: 3,
    goldThreshold: 7,
    platinumThreshold: 15,
    diamondThreshold: 30,
    starThreshold: 60,
    kingThreshold: 100,
  },
  {
    code: "marathon",
    name: "马拉松",
    description: "单日学习 120 分钟的天数",
    category: "milestone",
    icon: "Timer",
    bronzeThreshold: 1,
    silverThreshold: 3,
    goldThreshold: 7,
    platinumThreshold: 15,
    diamondThreshold: 30,
    starThreshold: 60,
    kingThreshold: 100,
  },
];
